### ISSUE TITLE
URL to 'document site' 404

### ISSUE THREAD

**Issue by jeremiah** [dxc-technology/halstack-react#1]
**Describe the bug**
URL to 'document site' 404's

**To Reproduce**

1. surf to halstack-react README.md
2. Click on "document site" under the "usage" section

**Expected behavior**
Working URL

**Screenshots**
N/A

**Comment by jsardid** [comment]
Thanks @jeremiah, that issue is fixed now.  

There could still exist some other issues like that one, since we are still finishing up with the transition from our private repositories and npm registries. Hopefully we'll have it all set by the end of this week.
