### ISSUE TITLE
[Dialog] Close button is displayed above the content of the component.

### ISSUE THREAD

**Issue by jsuarezgonz** [dxc-technology/halstack-react#1029]
**Describe the bug**
If you add enough content to the Dialog component, the close button appears above that content.

**To Reproduce**
Create a DxcDialog like this:

```
() => {
  const [isDialogVisible, setDialogVisible] = useState(false);
  const handleClick = () => {
    setDialogVisible(!isDialogVisible);
  };
  return (
    <>
        <DxcButton label="Open Dialog" onClick={handleClick}></DxcButton>
        {isDialogVisible && (
          <DxcDialog onCloseClick={handleClick}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. 
          </DxcDialog>
        )}
</>
  );
}
```

**Expected behavior**
The close button should have a certain margin to the content.

**Screenshots**
![image](https://user-images.githubusercontent.com/67998605/171405889-a045c9ac-04ff-4858-9ee4-29881fcd6282.png)

**Comment by GomezIvann** [comment]
We have agreed that the close action should behave like this. It's a user matter to avoid overlapping the Dialog content with the button. The other possible solutions are worse and more difficult to justify or understand from the user's point of view, so we stay like this for the moment.
