### ISSUE TITLE
On slider selected value should be displayed on top

### ISSUE THREAD

**Issue by pkumar589** [dxc-technology/halstack-react#103]
It's a business requirement that selected value should be shown right above the slider so that it's easy for users to relate to what they have selected. 

The slider should be "Responsive" also the value container should dynamically adjust to its value in it.

![image](https://user-images.githubusercontent.com/75477033/101625839-0b7e2100-3a42-11eb-8e49-1d79b9470bdd.png)

**Comment by jsardid** [comment]
Hello,

This is actually an issue with the design system guidelines. Right now they don't give any datails on how to display the selected value:
https://developer.dxc.com/design/components/slider

This issue has been identified and reported already in the design guidelines repository:
https://github.com/dxc-technology/halstack-style-guide/issues/12
