### ISSUE TITLE
DXCSelect option elements cropped when used with DxcBox

### ISSUE THREAD

**Issue by vicrodri** [dxc-technology/halstack-react#1032]
**Describe the bug**
- When including DxcSelect component inside a DxcBox the list of option elements is cropped by the container.

**To Reproduce**
- Add a DxcSelect component inside a DxcBox.

**Expected behavior**
- List of option elements fully visible when showing.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1343857/171437825-61347f0e-eeeb-423a-98d5-6d7ca041a0cc.png)

**Additional context**
- halstack-react v5.0.0

**Comment by GomezIvann** [comment]
It seems to be a problem with the Box rather than the Select. An `overflow: hidden` from the container is cutting off the Listbox. I'm currently working on it, thanks for the feedback!

**Comment by GomezIvann** [comment]
I've opened a new issue, you can follow [there](https://github.com/dxc-technology/halstack-react/issues/1047) our progress with the fix!
