### ISSUE TITLE
Support of SSN,TIN,email, phone number Formats should be available in component

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#104]
**Is your feature request related to a problem? Please describe.**
We have an requirement, that we want fields which are common like SSN, TIN, email, phone to be formatted automatically instead of us coding. Also it would be great if we can give an input to the CDK component that this is a numeric only field.
Its tedious to handle the simple activity to restrict alphabets on a field, we have to write code - a simple input to the coponent saying numeric should do that.
Also it would be nice, if we can mention the allowed size on the field. Like I want my text field is accept only 3 characters, there should be some attribute which I can set to 3, and the field will accept only 3.

**Describe the solution you'd like**
if we can mention the allowed size on the field. Like I want my text field is accept only 3 characters, there should be some attribute which I can set to 3, and the field will accept only 3.
There could be format attribute, which can be given values like numeric/alphanumeric/ssn/tim/phone/email which will either throw error on wrong enter, or will format the value or will not allow wrong characters in the field.

**Describe alternatives you've considered**
We had written onClick/onBlur methods, which does this for us, but its tedious and error prone as we have to do on every field.

Please do tell if the requirements are not clear, and any info needed from me?

**Comment by jsardid** [comment]
There are many feature requests in this issue. I think some of them we can actually implement them as part of the CDK.
We are going to think about which ones are appropriate.

In the meantime, the controlled version of the component allows you to implement any custom behaviour.

**Comment by ppurumala** [comment]
Please let us know what is decided, which one will be picked in your 21.2 release.

**Comment by pwadhwani** [comment]
Hi @jsardid, Could you please provide updates on this issue.

**Comment by pwadhwani** [comment]
@aweell @peibolsang @jsardid  Could you please share ETC on this ticket.

**Comment by sponnuswamydxc** [comment]
@jsardid Can you provide your latest updates on this issue ?

**Comment by jsardid** [comment]
Some of these formats (not all of them) have been implemented during this release and will be part of a numbered release in the following weeks.

**Comment by raquelarrojo** [comment]
`NumberInput` documentation available [here](https://developer.dxc.com/halstack/next/components/number-input/
).
`TextInput` documentation available [here](https://developer.dxc.com/halstack/next/components/text-input/).
