### ISSUE TITLE
Configurable component IDs for UI tests

### ISSUE THREAD

**Issue by DirkBaumannDXC** [dxc-technology/halstack-react#1054]
It would be very helpful if all components (e.g. buttons) provide the ability to specify an additional ID (e.g. "data-testid") that can be used for automated UI tests (e.g. Cypress: https://docs.cypress.io/guides/references/best-practices#Selecting-Elements ).

Especially in dynamic UIs it is sometimes difficult to identify the elements for an automated UI test.

**Comment by DirkBaumannDXC** [comment]
Hi @jsardid,

I see the problem that there is no direct relation to a DOM element in many cases and even if there is a relation this may change when the implementation of the DXC compontent changes. 

But it would be still useful for some specific components like buttons to have an identifier for the "typical" DOM element ("e.g. the DOM element with "type=button" that understand the "click" event). When having on a page multiple buttons which are dynamically visible or have language specific or dynamic labels such an ID would be very helpful to identify the button even when using the mentioned testing library. May be the DXC component not has a "data-testid" property, but a specific "data-clickable-id" property to make it clear to the user of the component. May be similar a "data-value-id" could be added for input or output components. 

Of course the test cases may has to be changed when the DXC implementation of the component changes, but I assume such a change in the test case is less work (or may be not even required in most cases) when identifying the clickable DOM element just by an ID.

Best regards,
 Dirk

**Comment by GomezIvann** [comment]
We have no plans on adding an `id` or `data-id` prop to our components. @jsardid is still valid and we share the same opinion.
