### ISSUE TITLE
Sidenav height in mobile

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-react#1178]
## Sidenav links cut off

The current sidenav height is not working in mobile:

![Screenshot 2022-07-14 at 22 03 55](https://user-images.githubusercontent.com/44420072/179073672-66c3bbd0-872c-408e-8fb6-901ea255ad6a.png)

The last item appears cut off since the calc for the height is calc(100vh-64), that works in desktop, but on mobile is not taking account the position of the container (112px from the top)

![Screenshot 2022-07-14 at 22 05 01](https://user-images.githubusercontent.com/44420072/179073915-96346ee6-5e9a-4268-9404-ff335406357e.png)

Btw, why 112px instead of 122px (64px from header + 58px from menu dropdown)?

## Android and iOS browser navigation bar

The problem using 100vh as height for the sidenav in mobile devices is that takes the outter-available-space value instead of the inner. And the browser bar is taking space inside this 100vh calculation.

This causes multiple links to be out of reach in mobile browsers:

![Group 1](https://user-images.githubusercontent.com/44420072/179074786-34e55eb9-dd55-46d1-8797-f9377ebd5113.png)

There are some workarounds that could work in this case. I leave here something I founded:
https://css-tricks.com/css-fix-for-100vh-in-mobile-webkit/

Hope it works!

### UPDATE

Extracting two issues from here:
- [x] #1201
- [x] iOS Safari is cutting off the sidenav

**Comment by GomezIvann** [comment]
About the 112px instead of 122px, seems that the height of the menu dropdown was changed after doing that calc, but not changed in there, which led to this inconsistency. Thanks for the feedback Alex 😃!

**Comment by GomezIvann** [comment]
Extracting two issues from here:
- [ ] Dropdown menu bar size is affecting the Application layout dispositioning.
- [ ] iOS Safari is cutting off the sidenav.

**Comment by GomezIvann** [comment]
With the recent updates to the Site (Flex component) and the Application Layout, the height of the Sidenav seems to now work fine in iPhone and not being cut off.

![image](https://user-images.githubusercontent.com/44321109/183093574-14d1d26e-4e4b-4b3e-ade1-981df94c7df6.png)

So I mark this issue as closed.
