### ISSUE TITLE
DxcDate does not work with React 17.0.1

### ISSUE THREAD

**Issue by gpfeifer** [dxc-technology/halstack-react#120]
**Describe the bug**
DxcDate does not work with React 17.0.1. The datepicker to choose the date does not appear

**To Reproduce**

1. Create a new React App using `create-react-app`
2. npm install `@dxc-technology\halstack-react`
3. npm install `styled-components`
4. Use a DxcDate and try to choose a date

**Expected behavior**
The datepicker to choose a date should appear

**Comment by jsardid** [comment]
We are actually inheriting these incompatibilities from third party libraries we are using in the CDK implementation. And we are already working in solving these incompatibilities with react 17.

Thanks for the feedback!

**Comment by jsardid** [comment]
Fix included in version 3.0.0
