### ISSUE TITLE
Need ability to put a currency symbol and amount formatting on Slider component

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#122]
Need ability to put a currency symbol and amount formatting on Slider component

We want the amount on the slider to be displayed as $10,000 and $1,00,000.
Please note the dollar sign and comma in the amount

![Slider](https://user-images.githubusercontent.com/72923647/100224616-0f3e7d80-2f43-11eb-85ae-a3e5f125d434.jpg)

Please do tell us if this is possible in any way?

**Comment by marcialfps** [comment]
In the last version we added a new prop called **labelFormatCallback**. This is a function that will be used to format the labels displayed next to the slider. 
You can see an example here: https://developer.dxc.com/tools/react/next/#/components/slider
