### ISSUE TITLE
Select pop over in firefox

### ISSUE THREAD

**Issue by Jialecl** [dxc-technology/halstack-react#1242]
The select pop over does not apply the correct width in firefox.
But the one inside the paginator seems to be working as intended.

![image](https://user-images.githubusercontent.com/12238686/184868008-dc0733f4-89a2-47f8-bdf2-6dafdbdcefbf.png)

**Comment by GomezIvann** [comment]
Can you explain a bit more about how to reach the bug? After playing with the select on Firefox I can't reproduce the problem issue

![image](https://user-images.githubusercontent.com/44321109/186116764-13f17858-ad87-44b9-9aaa-5144fab205ee.png)

**Comment by Jialecl** [comment]
I launched the old app in which we have all the components.
I was trying to reproduce the issue in different projects and that's the one in which I reproduced the issue consistently.

**Comment by Jialecl** [comment]
To reproduce the issue it seems that the select has to be inside a HalstackProvider
`<HalstackProvider>
        <DxcSelect label="testtttt" options={single_options} />
      </HalstackProvider>`
also it is reproducible only the first time the component is rendered in a new tab.
