### ISSUE TITLE
Compare function to use in ResultsTable sortable columns

### ISSUE THREAD

**Issue by AlanPadi95** [dxc-technology/halstack-react#1271]
**Is your feature request related to a problem? Please describe.**
In ResultsTable, complex values can't be sorted because the comparator can not perform comparisons between non-primitive values.

**Describe the solution you'd like**
I think you can just add a prop to the ResultsTable columns that give us the possibility to use a custom comparator function.

**Comment by raquelarrojo** [comment]
Is this still needed? @AlanPadi95

**Comment by AlanPadi95** [comment]
Yes!

We need a way to use a custom `compareTo` for each column of a table in order to sort complex elements like versions (i.g.: `1.0.1+3` < `1.0.1+31`)

Thanks!

**Comment by Mil4n0r** [comment]
The decision has been made that, in the current state of the component, sortValue is a sufficient tool to cover all proposed cases. In case it is not sufficient in the future, the inclusion of a custom comparator will be considered.
