### ISSUE TITLE
Replace and delete uuid npm library

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-react#1274]
A few releases ago we started to use [uuid npm library](https://www.npmjs.com/package/uuid) for id generation in our components when needed. Since then, React has launched a new version of its framework ([React 18](https://es.reactjs.org/blog/2022/03/29/react-v18.html)) which gives us, the developers, a new hook called [`useId`](https://es.reactjs.org/docs/hooks-reference.html#useid) to do this task, so we don't have to relay in external libraries or implement our own algorithm.

The tasks here are:

- [x] Find every usage of the `uuidv4()` method and replace it with the new `useId()` hook.

![image](https://user-images.githubusercontent.com/44321109/190641749-31360053-97ef-4614-96cf-e81910359da9.png)

- [x] Delete the library `uuid` from /lib dependencies.

**Comment by Lisa159** [comment]
In stand by for further discussions. The use of this hook will force the user to migrate to React 18.

**Comment by Mil4n0r** [comment]
I would like to revisit this topic.
