### ISSUE TITLE
Update component's size `fitContent`

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-react#1277]
Most of our components have the prop `size` with the value `fitContent`, which should behave as CSS value `fit-content`. That is, the component must use the available space within the box that contains it ([CSS fit-content](https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content)).

But, currently, `fitContent`'s value is not what doing what its naming says, since its value is [`unset`](https://developer.mozilla.org/en-US/docs/Web/CSS/unset) instead of what I mentioned earlier. We need to update this in every component affected, because it can lead to unexpected behaviour for the users (for example, https://github.com/dxc-technology/halstack-react/issues/1082).

**Comment by Lisa159** [comment]
Components with this issue:
- Alert
- Box
- Button
- Checkbox
- Dropdown
- Switch
- Tag
