### ISSUE TITLE
Read-only mode for input/form components

### ISSUE THREAD

**Issue by vicrodri** [dxc-technology/halstack-react#1290]
**Is your feature request related to a problem? Please describe.**
We found ourselves in the need of having a read only mode on input elements, not just disabled, to keep the global look and feel of the Halstack Design System. Is it out of scope or is it possible to be added in future releases?

**Describe the solution you'd like**
One example for input text elements could be somethign like this: 
![imagen](https://user-images.githubusercontent.com/1343857/191519662-51b988af-c90a-43e8-962e-64d5ebd38276.png)

The first element could be the read-only mode for an input text, added the second for comparison.

**Describe alternatives you've considered**
Disabled does not cover our use cases.

**Comment by GomezIvann** [comment]
First of all, thanks for the feedback Viti.

We already have an open [issue](https://github.com/dxc-technology/halstack-react/issues/834) for this.

**Comment by vicrodri** [comment]
Great Iván, I will close this then since you already have it,  Thanks a lot.
