### ISSUE TITLE
Deprecate `padding` prop from affected components

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-react#1297]
This issue is the result of discussion #1266. For further details, go and check it. 

The list of affected components is:
- [x] Deprecate `padding` prop from Accordion and Accordion Group
- [x] Deprecate `padding` prop from Box
- [x] Deprecate `contentPadding` prop from Card
- [x] Deprecate `padding` prop from Dialog
- [x] Deprecate `padding` prop from Footer
- [x] Deprecate `padding` prop from Header

**Comment by Jialecl** [comment]
Instead of removing the components, we decided to mark the prop as deprecated at least in the meantime.
