### ISSUE TITLE
Accessibility concerns with Quick Nav component

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-react#1316]
I launched [Lighthouse](https://developer.chrome.com/docs/lighthouse/overview/) on the new site to test our accessibility and performance and I found some issues with the Quick Nav component. 

<img width="582" alt="Sin título" src="https://user-images.githubusercontent.com/44321109/193024226-3241b4b3-d9f0-4253-a82f-79beb85af112.png">

<img width="524" alt="image" src="https://user-images.githubusercontent.com/44321109/193024352-c9af877d-70f0-4a17-8240-6bbf5f1edbd3.png">

After these results and checking the DOM of the component I saw that we are making some major accessibility mistakes. In the [Quick Nav example](https://developer.dxc.com/halstack/next/components/quick-nav/#basic-usage):

![image](https://user-images.githubusercontent.com/44321109/193024855-f8eeb9e4-0012-48f6-8616-96c84c59873d.png)

![image](https://user-images.githubusercontent.com/44321109/193024953-26fa32ca-d6b8-49e0-bc55-4b8d90cc42b4.png)

The problems here are:

1. `<li>` tags **must** always be contained inside `<ul>` or `<ol>` as direct parent, so screen readers can identify the whole as a list and read it in a special way (this [article](https://dequeuniversity.com/rules/axe/4.4/listitem?utm_source=lighthouse&utm_medium=lr) explains it in detail).
2. The same on the other way around, `<ul>` or `<ol>` **must** only contain `<li>` tags as direct childs (this [article](https://dequeuniversity.com/rules/axe/4.4/list?utm_source=lighthouse&utm_medium=lr) explains it in detail).

**Comment by eriesgo** [comment]
Good catch @GomezIvann 

For me this is an issue that we will need to add our our backlog.

**Comment by GomezIvann** [comment]
Agree, this is an important accessibility issue.

![image](https://user-images.githubusercontent.com/44321109/193214240-f04971b4-774a-42df-bb16-8f606178ae55.png)
