### ISSUE TITLE
Checkbox position in scrollable multiselect

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-react#1355]
When options are checked in a select multiple dialog with overflowing content, scrolling down causes the checkbox "check" to behave as sticky.

Image for reference:

![image](https://user-images.githubusercontent.com/44420072/198422026-345ac98a-b795-4b43-8440-749a00a03931.jpeg)

**Comment by GomezIvann** [comment]
You are right Alex, seems that the new reimplementation of the Checkbox has some trouble when is inside a scrollable container. 

![image](https://user-images.githubusercontent.com/44321109/199676829-dcb94c08-0319-4b39-9803-f4bdb6d993d9.png)
