### ISSUE TITLE
Text Input's action executes form submit when it is clicked.

### ISSUE THREAD

**Issue by raquelarrojo** [dxc-technology/halstack-react#1363]
**Describe the bug**
If the Text Input is used inside a form, when its action is clicked, it executes the submit of the form instead of the onClick's action.

**To Reproduce**
Use the Text Input inside a form. Click on the Text Input's action.

**Expected behaviour**
Text Input's action should be executed, instead of the submit of the form.

**Comment by GomezIvann** [comment]
This is probably caused because we are not defining the type of the actions (button elements) as `"button"`. By default, they behave as `"submit"` buttons although they are not identified as one.
