### ISSUE TITLE
DxcApplicationLayout.Header.Dropdown wrong optionsList size

### ISSUE THREAD

**Issue by vicrodri** [dxc-technology/halstack-react#1374]
**Describe the bug**
After upgrading from v6.0.0 to v7.0.0, the component DxcApplicationLayout.Header.Dropdown displays the option list with the wrong size, the list is shrunk to minimum width instead of showing the options' values completely as it did.

**To Reproduce**
I attached our component code:
```

<DxcApplicationLayout.Header
      underlined={true}
      onClick={() => {}}
      padding={{ left: "medium", right: "large" }}
      content={
        <HeadingContainer>
          <DxcHeading
            level={3}
            text="DXC Assure Solution Composer"
            weight="normal"
            margin={{ left: "medium", right: "medium" }}
          />
          <DxcFlex>
            <DxcApplicationLayout.Header.Dropdown
              label={userName}
              options={optionsUser}
              iconSrc={accountIcon}
              iconPosition="before"
              onSelectOption={signOut}
            ></DxcApplicationLayout.Header.Dropdown>
          </DxcFlex>
        </HeadingContainer>
      }
    ></DxcApplicationLayout.Header>
```

**Expected behaviour**
Header dropdown options to be displayed as they did on v6.

**Screenshots**
- HDS v6.0.0
  - **Chrome**
![imagen](https://user-images.githubusercontent.com/1343857/200868767-6e0568b8-b1c9-4f82-9bad-5d89e35c2546.png)
  - **Firefox**
![imagen](https://user-images.githubusercontent.com/1343857/200869135-a6c04109-a4f4-4f17-a635-b267c936064e.png)

- HDS v7.0.0
  - **Chrome**
![imagen](https://user-images.githubusercontent.com/1343857/200869689-ff4a7084-b370-44dd-b358-9a26a96d1f1f.png)
  - **Firefox**
![imagen](https://user-images.githubusercontent.com/1343857/200869928-ebe76490-e20d-45de-ac68-716392585dd7.png)

**Comment by marcialfps** [comment]
Hi @vicrodri, I'm trying to reproduce the error but for now, I'm not able. Can you attach the styles of the `HeadingContainer`?
Thank you! ✌🏼

**Comment by vicrodri** [comment]
I'm sorry I miseed this, here they are

```
const HeadingContainer = styled.div`
  display: flex;
  flex-direction: row;
  align-items: center;
  width: 100%;
  justify-content: space-between;
  position: relative;
  color: black;
  :before {
    width: 1.2px;
    height: 26px;
    background-color: black;
    display: block;
    content: "";
    position: absolute;
    left: 0px;
  }
`;
```

**Comment by marcialfps** [comment]
@vicrodri we fixed this error, but we want to add that your use case is not correct. You should render the dropdown when data is available. If you want to fix the error without changing your version you just need to first load data and then render the component:

```
<DxcApplicationLayout.Header
      underlined={true}
      onClick={() => {}}
      padding={{ left: "medium", right: "large" }}
      content={
        <HeadingContainer>
          <DxcHeading
            level={3}
            text="DXC Assure Solution Composer"
            weight="normal"
            margin={{ left: "medium", right: "medium" }}
          />
          <DxcFlex>
            { 
              userName && 
              (<DxcApplicationLayout.Header.Dropdown
              label={userName}
              options={optionsUser}
              iconSrc={accountIcon}
              iconPosition="before"
              onSelectOption={signOut}
            ></DxcApplicationLayout.Header.Dropdown>)
            }
          </DxcFlex>
        </HeadingContainer>
      }
    **></DxcApplicationLayout.Header>**
```
