### ISSUE TITLE
data-title is required for table responsive in mobile view

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#140]
**Is your feature request related to a problem? Please describe.**

data-title is required for table responsive in mobile view.
**This request is for DXCResultsetTable component.**
As CDK table is not responsive  in mobile view, to make it responsive we need one attribute to make it responsive 
That is “data-title” in table th tags . Like this  -->  <th data-title="">
and same support is required for <td> tags too. Like This <td data-title="">

The value in data-title of td, should be given in data-title of th tag of table, in order for the column name to be visible in mobile view.

The mobile view is like this now: the column names are missing.
![Screenshot (1760)](https://user-images.githubusercontent.com/72923647/105025069-d6b6ae00-5a72-11eb-9973-f68de4011674.png)

Can you please do that, similar to this below:
![Screenshot (1749)](https://user-images.githubusercontent.com/72923647/105024860-95be9980-5a72-11eb-9b72-289108067b3d.png)

For your reference have attached a html table structure
[RWD Table.zip](https://github.com/dxc-technology/halstack-react/files/5835390/RWD.Table.zip)

**Comment by ppurumala** [comment]
Please take this one on Priority. We need this for our business need.

**Comment by jsardid** [comment]
Hi @ppurumala,

I understand you implemented responsiveness by using a custom "data-title" attribute. But I don't really think that was required.

Maybe there is something I'm missing, could you explain further? Could this be happening because you are using a third party library like bootstrap for the tables?

**Comment by jsardid** [comment]
We are closing this one.
Please reopen if this is still an issue.
