### ISSUE TITLE
Autosuggest option values not working properly

### ISSUE THREAD

**Issue by Lisa159** [dxc-technology/halstack-react#1416]
**Describe the bug**
Writing certain strings in the autosuggest will show error because we are converting the value into a regular expression inside the component.

If we write for example `*`, the value of the autosuggest will be converted to regex. Because `*` is a wrong regular expression it will show this error.

**To Reproduce**
1. Create a new React App using `create-react-app`.
2. Install the `@dxc-technology\halstack-react` dependencies and run the app.
3. Write the following example:
```
  const countries = ["*", "Albania"];
  const [value, setValue] = useState("");
  const onChange = ({ value }) => {
    setValue(value);
  };
  const onBlur = ({ value }) => {
    setValue(value);
  };

  const callbackFunc = (newValue) => {
    const result = new Promise((resolve) =>
      setTimeout(() => {
        resolve(
          newValue
            ? countries.filter((option) =>
                option.toUpperCase().includes(newValue.toUpperCase())
              )
            : countries
        );
      }, 1500)
    );
    return result;
  };
  return (
    <DxcInset space="2rem">
      <DxcTextInput
        label="Enter your country"
        value={value}
        onChange={onChange}
        suggestions={callbackFunc}
        onBlur={onBlur}
      />
    </DxcInset>
  );
```
4. Click the component and select the option `*`.
5. See the error.

**Expected behaviour**
It should select the option.

**Screenshots**
![image](https://user-images.githubusercontent.com/34685461/207050972-ef60c47d-2d2f-43b9-8ad3-3f47a267e39f.png)

![image](https://user-images.githubusercontent.com/34685461/207049167-b3541e6e-44ed-4e0e-9292-91b1ebc3cd35.png)

![image](https://user-images.githubusercontent.com/34685461/207049076-c7d9dc62-da04-48fd-b630-fd300c6492db.png)

![image](https://user-images.githubusercontent.com/34685461/207049624-2364f698-a518-4843-af79-dca366120bcd.png)

**Add labels**
Text input, autosuggest.

**Comment by HanojHanu** [comment]
Thanks for following up this #1414 issue.

@Lisa159
