### ISSUE TITLE
Accordion theming strategy issue

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-react#1426]
**Describe the bug**
The `accentColor` token is affecting the focus of the Accordion component, when I think it shouldn't because, apart from the fact that this is the only component whose focus color is being changed by an opinionated theme token, I consider this going against the fundamentals of our theming strategy since the focus a fundamental design opinion that shouldn't be affected by the theming.

![image](https://user-images.githubusercontent.com/44321109/209671260-637d2869-83bc-4954-8e4c-6422fac9e77a.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/44321109/209670718-844be364-d343-4fca-a059-c110a0278941.png)

**Comment by raquelarrojo** [comment]
Linked to #1364

**Comment by raquelarrojo** [comment]
Totally agree. Fixed after the review of the opinionated theme.
