### ISSUE TITLE
Dropdown - Menu ( options size fit )

### ISSUE THREAD

**Issue by HanojHanu** [dxc-technology/halstack-react#1438]
**Describe the bug**
Dropdowm menu options should fit based on content length.

---- 
**To Reproduce**
Include steps to reproduce the behaviour.
``` jsx
() => {
  const selectOption = (value) => {
    console.log(value);
  };
  const options = [
    {
      value: 1,
      label: "Android",
    },
  ];

  return (
    <DxcInset space="2rem">
      <DxcDropdown
        icon={<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 512"><path d="M64 360c30.9 0 56 25.1 56 56s-25.1 56-56 56s-56-25.1-56-56s25.1-56 56-56zm0-160c30.9 0 56 25.1 56 56s-25.1 56-56 56s-56-25.1-56-56s25.1-56 56-56zM120 96c0 30.9-25.1 56-56 56S8 126.9 8 96S33.1 40 64 40s56 25.1 56 56z"/></svg>}
        caretHidden={true}
        options={options}
        onSelectOption={selectOption}
        size="small"
        padding="xxsmall"
      ></DxcDropdown>
    </DxcInset>
  );
}
```
Example:

1. Create a new React App using `create-react-app`.
2. Install the `@dxc-technology\halstack-react` dependencies and run the app.
3. Click on '...'.
4. Scroll down to '...'.
5. See the error.

**Expected behaviour**
![image](https://user-images.githubusercontent.com/53425981/212043679-0d79e472-a48d-4563-85c6-53238e72a770.png)
https://codesandbox.io/s/dropdown-432qn0?file=/index.html

-----
**Screenshots**

![image](https://user-images.githubusercontent.com/53425981/212034993-9a117f7d-7230-4736-bfaa-84107b0bc0ec.png)

**Comment by GomezIvann** [comment]
hi @HanojHanu

Your request seems fair. In the past, we designed the component with the idea of a button and a menu with the same width, but this premise seems to fit better a select component rather than a dropdown, which is a navigational component. Anyways, we will study this as part of the component re-design that will take place shortly (#835). You can track our progress there!

To conclude, be careful with the `padding` prop in your code snippet as it does not exist in the component.

Thanks for the feedback 😃!

**Comment by HanojHanu** [comment]
Yes, just tring `padding` to remove unwanted space around my 3-dot menu..

**Comment by GomezIvann** [comment]
That space is because you are adding a fixed size (`size="small"`). Try to remove it and the icon should be centred.

![image](https://user-images.githubusercontent.com/44321109/212305747-35f473ac-41c0-45af-827c-f5c665a8032e.png)

**Comment by GomezIvann** [comment]
The space around the icon is a design decision and can't be removed. As I said, this component anatomy was inherited from Material UI and is a bit outdated, we have planned a [re-design](https://github.com/dxc-technology/halstack-react/issues/835) at a certain point in the future and we will consider this scenario.
