### ISSUE TITLE
Tabs component visual defects

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-react#1442]
**Describe the bug**
When using an image (URL) as an icon for the first tab, the border-bottom does not reach the end.

![image](https://user-images.githubusercontent.com/44321109/212894357-3557df4d-e498-4ea9-8860-bdade9e67ce8.png)

Also, the border-bottom is misaligned when using both an image or an SVG with a bigger size than 22x22.

![image](https://user-images.githubusercontent.com/44321109/212893958-6c5a94d4-760a-4294-b01a-3735508de43b.png)

**Expected behaviour**
The border-bottom should occupy the width of the button (tab), neither more nor less.

**Comment by Mil4n0r** [comment]
I haven't been able to replicate either of both bugs on my end playing with the icons from Storybook containers. Can you share some extra details?

**Comment by GomezIvann** [comment]
I can't reproduce them either. We are going to close this, a bit odd.
