### ISSUE TITLE
Phone Number Field ( ❗ Important Feature )

### ISSUE THREAD

**Issue by hanoj-budime** [dxc-technology/halstack-react#1460]
**Is your feature request related to a problem? Please describe.**
PhoneNumberField allows users to input phone numbers.

**Describe the solution you'd like**
Import the PhoneNumberField component and provide a label for accessibility/usability as well as a defaultDialCode which will auto-populate the dial code select field.

![image](https://user-images.githubusercontent.com/53425981/218006614-6ca435de-d770-4145-aaa0-44145a2a2a0f.png)

**Additional context**
https://ui.docs.amplify.aws/react/components/phonenumberfield#dial-code-select-properties

# Demo
https://ui.docs.amplify.aws/react/components/phonenumberfield#demo

**Comment by GomezIvann** [comment]
We understand the value of this component and can be a good proposal. We will investigate it and think if it fits our design system form components.

**Comment by HanojHanu** [comment]
Any updates here..

**Comment by hanoj-budime** [comment]
https://github.com/bl00mber/react-phone-input-2

**Comment by GomezIvann** [comment]
Hello @hanoj-budime!

We have no plans of adding a Phone Field Input shortly since it can be achievable by combining our `DxcTextInput` with a `DxcSelect`. Here is a short example:

![image](https://github.com/user-attachments/assets/2e3072be-0e69-462f-81fa-c15ccfd32878)
```
import {
  DxcFlex,
  DxcInset,
  DxcSelect,
  DxcTextInput,
  DxcTypography,
} from "@dxc-technology/halstack-react";

function App() {
  return (
    <DxcInset space="2rem">
      <DxcFlex direction="column">
        <DxcTypography fontSize="0.875rem" fontWeight="600">
          Phone number
        </DxcTypography>
        <DxcTypography fontSize="0.75rem" fontStyle="italic">
          Please, enter your phone number
        </DxcTypography>
      </DxcFlex>
      <DxcFlex gap={"0.5rem"}>
        <DxcSelect
        defaultValue={"1"}
          options={[
            { label: "+1", value: "1" },
            { label: "34", value: "+34" },
          ]}
          size="small"
        />
        <DxcTextInput placeholder="234-567-8910" />
      </DxcFlex>
    </DxcInset>
  );
}

export default App;
```

I hope this helps!

**Comment by hanoj-budime** [comment]
@GomezIvann,

![image](https://github.com/user-attachments/assets/f0b37ff3-b48a-4d69-a6ec-f852bb128725)

I know that DxcSelect and DxcTextInput are combined to create the phone number component, but what about width control for DxcSelect? Didn't you notice that DxcSelect is taking up too much width? What will you do about this?

[Perview: codesandbox.io](https://codesandbox.io/p/devbox/phone-number-forked-v3r2dg?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzqu3ovx0009356i3u1nyren%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzqu3ovx0002356ijzmmroo1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzqu3ovx0006356i780c2tbm%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzqu3ovx0008356i0bn8nvg7%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzqu3ovx0002356ijzmmroo1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzqu3ovw0001356ivk43ngtj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clzqu3ovx0002356ijzmmroo1%2522%252C%2522activeTabId%2522%253A%2522clzqu3ovw0001356ivk43ngtj%2522%257D%252C%2522clzqu3ovx0008356i0bn8nvg7%2522%253A%257B%2522id%2522%253A%2522clzqu3ovx0008356i0bn8nvg7%2522%252C%2522activeTabId%2522%253A%2522clzqumnoa007h356itiv3a6zh%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzqu3ovx0007356i80d9anui%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%257D%252C%257B%2522type%2522%253A%2522CHANGELOG%2522%252C%2522id%2522%253A%2522clzqumnoa007h356itiv3a6zh%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzqu3ovx0006356i780c2tbm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzqu3ovx0003356iercspur0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clzqu3ovx0004356iman7b9ec%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clzns8xbx000sdlg2g3cv3fdp%2522%257D%252C%257B%2522id%2522%253A%2522clzqu3ovx0005356i7ch75fdi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clzns9ar3000ydlg2dhefc7n9%2522%257D%255D%252C%2522id%2522%253A%2522clzqu3ovx0006356i780c2tbm%2522%252C%2522activeTabId%2522%253A%2522clzqu3ovx0003356iercspur0%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by GomezIvann** [comment]
> @GomezIvann,
> 
> ![image](https://private-user-images.githubusercontent.com/53425981/357007399-f0b37ff3-b48a-4d69-a6ec-f852bb128725.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTg4MjIsIm5iZiI6MTcyMzQ1ODUyMiwicGF0aCI6Ii81MzQyNTk4MS8zNTcwMDczOTktZjBiMzdmZjMtYjQ4YS00ZDY5LWE2ZWMtZjg1MmJiMTI4NzI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDEwMjg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YmFhMTMzOGU5NDU2MjNjODBiNWJmOGRlY2I3MTUzZmYyMDA5Yjk4NmY3ZGIxZTUxY2FlYWFiNWI1OGJhMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DWc4jtAavmf0iiA37AYLMYrkFQ5R-0i8p9HPpL_gVcU)
> 
> I know that DxcSelect and DxcTextInput are combined to create the phone number component, but what about width control for DxcSelect? Didn't you notice that DxcSelect is taking up too much width? What will you do about this?
> 
> [Perview: codesandbox.io](https://codesandbox.io/p/devbox/phone-number-forked-v3r2dg?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzqu3ovx0009356i3u1nyren%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzqu3ovx0002356ijzmmroo1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzqu3ovx0006356i780c2tbm%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzqu3ovx0008356i0bn8nvg7%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzqu3ovx0002356ijzmmroo1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzqu3ovw0001356ivk43ngtj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clzqu3ovx0002356ijzmmroo1%2522%252C%2522activeTabId%2522%253A%2522clzqu3ovw0001356ivk43ngtj%2522%257D%252C%2522clzqu3ovx0008356i0bn8nvg7%2522%253A%257B%2522id%2522%253A%2522clzqu3ovx0008356i0bn8nvg7%2522%252C%2522activeTabId%2522%253A%2522clzqumnoa007h356itiv3a6zh%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzqu3ovx0007356i80d9anui%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%257D%252C%257B%2522type%2522%253A%2522CHANGELOG%2522%252C%2522id%2522%253A%2522clzqumnoa007h356itiv3a6zh%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzqu3ovx0006356i780c2tbm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzqu3ovx0003356iercspur0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clzqu3ovx0004356iman7b9ec%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clzns8xbx000sdlg2g3cv3fdp%2522%257D%252C%257B%2522id%2522%253A%2522clzqu3ovx0005356i7ch75fdi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clzns9ar3000ydlg2dhefc7n9%2522%257D%255D%252C%2522id%2522%253A%2522clzqu3ovx0006356i780c2tbm%2522%252C%2522activeTabId%2522%253A%2522clzqu3ovx0003356iercspur0%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A15%257D)

I updated the example above. Use `size="fillParent"` and a `DxcGrid` to manage the sizes.
