### ISSUE TITLE
Issue Link ( add in footer )

### ISSUE THREAD

**Issue by HanojHanu** [dxc-technology/halstack-react#1461]
**Is your feature request related to a problem? Please describe.**
Halstack [Developer website](https://developer.dxc.com/halstack/8/overview/introduction/
) include[ Issue link](https://github.com/dxc-technology/halstack-react/issues
) in footer

<img width="618" alt="image" src="https://user-images.githubusercontent.com/53425981/218008774-f9b763cd-1f59-4a52-aa12-ea52a975e003.png">

This will helps us - to request "Bug" or "Feature" easily

**Comment by GomezIvann** [comment]
I agree with you Hanoj, we are missing some sort of "quick access" functionality with our repository on GitHub. We will consider and discuss this.

Thanks for the feedback as always! 🙂
