### ISSUE TITLE
SPIKE - Consider Badge as an exported component of the CDK

### ISSUE THREAD

**Issue by raquelarrojo** [dxc-technology/halstack-react#1514]
Consider a new `DxcBadge` component to be exported as part of the CDK.

This Badge is now internal and is part of the Tabs component, but we could rethink it and consider it as a component.

Current implementation:
![image](https://user-images.githubusercontent.com/10975289/223421297-69bfdc56-a85f-4c15-8776-d96a729d338d.png)

**Comment by GomezIvann** [comment]
This use case is going to be covered by our future Tag component. There's no need to export our internal `DxcBadge` anymore.
