### ISSUE TITLE
Pop up components keyboard interactions inside a dialog

### ISSUE THREAD

**Issue by Jialecl** [dxc-technology/halstack-react#1515]
Right now closing a dropdown or a calendar using the `ESC` key also closes the dialog itself.

The popup component should be able to be closed without closing the dialog.

One of the possible solutions is implementing `event.stopPropagation()`, but this needs to be further investigated to see if it is the best solution and if there is any other keys that may have similar issues.

**Comment by Mil4n0r** [comment]
The method used in #1817 to fix the issue feels inappropiate for such an specific / simple issue. We have to look for a better solution that doesn't involve adding too much code to the current and future components with keyboard interaction.
