### ISSUE TITLE
Grid layout not available In our halstack-react

### ISSUE THREAD

**Issue by Ragavreddy** [dxc-technology/halstack-react#1526]
We don't have any component for supporting grid system, so we had to use another third party library to implement grid system and responsive part of the layout. 

Please provide required components in our halstack-react library.

**Comment by GomezIvann** [comment]
Hi @Ragavreddy!

I'm happy to report that the first version of the Grid is already available [here](https://developer.dxc.com/halstack/next/components/grid/). Please, check it out and feel free to share your comments and thoughts about it 🚀 (https://github.com/dxc-technology/halstack-react/discussions/new/choose).

I'm closing this issue, thanks for your patience.
