### ISSUE TITLE
Halstack - Design System - Quick View of available versions

### ISSUE THREAD

**Issue by HanojHanu** [dxc-technology/halstack-react#1539]
**Is your feature request related to a problem? Please describe.**
Finding the latest available version for others is very difficult.

Why don't we support "Listing all the available versions" on HalstackDesign System Site?

For Example

![image](https://user-images.githubusercontent.com/53425981/229111818-ca1b3991-427a-4099-ac8d-fa11336aae2f.png)

**Comment by GomezIvann** [comment]
Hello @HanojHanu!

You are right. When migrating to the new documentation page, we lost the feature to switch between different Halstack versions. The reason for this is that, for us, it wasn't the best possible solution, so we decided to rethink and implement a new procedure for this functionality. For the moment, the only way is from the section "Previous documentation sites"

![image](https://user-images.githubusercontent.com/44321109/229492028-38a6265e-a31e-4b1e-af8b-15cc89a5d040.png)

But this is only a temporary solution. Our goal is to discuss, design and implement some sort of **Releases** page which collects the version history of [halstack-react](https://github.com/dxc-technology/halstack-react/releases) repo in GitHub. From it, you would be able to switch between different versions of halstack, see the changes of each version, etc. Here are some examples that can be used for guidance:

Primer Design System: https://primer.style/news/
Braid Design System: https://seek-oss.github.io/braid-design-system/releases
Carbon Design System: https://carbondesignsystem.com/all-about-carbon/releases/
