### ISSUE TITLE
Accordian Group Missing in developers toolkit

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#156]
Issue: Accordian Group Missing in developers toolkit

Our designer wants a Accordian group on the page. There is a component for that in his designer toolkit, however in developers toolkit it is missing. We can implement individual accordian, but group is not there.

Please tell us on how can we achieve this? Thank you

**Comment by jsardid** [comment]
We will take care of this one ASAP.

Thanks for the feedback.
