### ISSUE TITLE
Jest Test - issue "Focus"

### ISSUE THREAD

**Issue by HanojHanu** [dxc-technology/halstack-react#1586]
**Describe the bug**
I'm facing issue - Jest test case - after updating to Halstack 9
Dialog-Box, Any idea ?

**To Reproduce**
``` cmd
npm run test:ci
```
Example:

1. Install the `@dxc-technology\halstack-react@9.0.0` dependencies and run the app.

**Screenshots**
![image](https://user-images.githubusercontent.com/53425981/235941061-bfd0db9f-658d-4341-ac0e-3a823c5ed564.png)

**Comment by GomezIvann** [comment]
Hi @HanojHanu!

We have been working on this issue. After some research, it looks like it is a problem related to the `jsdom` library of Jest (there's an issue with this https://github.com/dperini/nwsapi/issues/81), which uses internally another library called [nwsapi](https://github.com/dperini/nwsapi) that has some troubles interpreting query with `:not(...)` selector. 

We have been working on a workaround for this problem. You can follow the progress here https://github.com/dxc-technology/halstack-react/pull/1595.

Thanks for the feedback and the patience!

**Comment by HanojHanu** [comment]
![image](https://github.com/dxc-technology/halstack-react/assets/53425981/0f219557-f5e7-448d-979d-53280e35f657)

it's still not working..

**Comment by HanojHanu** [comment]
@GomezIvann

**Comment by HanojHanu** [comment]
![image](https://github.com/dxc-technology/halstack-react/assets/53425981/d6cc25b0-c2c8-4453-b95b-c789ebd3ec43)


# Fixed & Working fine in 10.0.0v

@GomezIvann thanks

**Comment by GomezIvann** [comment]
Great!! 🚀
