### ISSUE TITLE
Responsiveness using DxcGrid and DxcFlex

### ISSUE THREAD

**Issue by saikrishna-gattupalli** [dxc-technology/halstack-react#1602]
Hi,

I am using DxcGrid and DxcFlex for our application development. But I am facing issues with responsiveness. Based on the screen size, we may have to show content column wise or row wise, but unable to, since we are declaring in the component whether to show content in column wise or row wise and unable to change it based on screen size. If we can see below image, the three dropdowns are resized in the given space itself. Please let me know if there is a way to achieve responsiveness?
<img width="358" alt="image" src="https://github.com/dxc-technology/halstack-react/assets/16523669/5383656f-63fa-4bb7-9dc7-f596b517a9a4">

**Comment by GomezIvann** [comment]
Hi @saikrishna-gattupalli!

First of all, sorry for the late response. What you are trying to do can be achieved in two ways:

1. Custom containers and endpoints with your own media queries. This will give you full freedom to customize whether the inputs should wrap into the next line.
2. Use the `DxcGrid` container. You must use a special value called `auto-fit` in this case. The code would look like this.
```
    <DxcGrid
      templateColumns={["repeat(auto-fit, minmax(140px, 1fr))"]}
      gap="2rem"
    >
      <DxcTextInput label="Long label" size="fillParent" />
      <DxcTextInput label="Very very long label" size="fillParent" />
      <DxcTextInput label="Label" size="fillParent" />
    </DxcGrid>
```
This code is telling the grid elements to shrink until they reach 140px width (when the screen is resized). In that case, jump to the next row. If the screen gets bigger and they have more than 140px each, grow them all and split the space evenly.

**Comment by GomezIvann** [comment]
Since there have been no further responses, we consider this issue resolved and proceed to close it.

Thanks.
