### ISSUE TITLE
Typography allows invalid HTML tags in `as` prop

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-react#1621]
**Describe the bug**
Some HTML tags we consider valid for `as` prop of the DxcTypography component are not so. For example, the tags `<br />` and `<col />` do not have children, both in HTML and React, which is causing our component to break. We need to restrict the possible values of this prop.

**Comment by Mil4n0r** [comment]
I see 2 possible approaches here:

1. Accepting any string that is considered a tagname in the "as" parameter except for those that match a void element tag (br, img, area...)
2. Accepting only those "as" parameters that match with what is expected from a Typography component (we would have to discuss which ones those should be, aside from the typical span, div, p, h1, h2, h3...)

I honestly think that the second approach would be more appropiate.

**Comment by GomezIvann** [comment]
I agree, the second option is the best one. But first, we need to discuss the tags that we want to allow.

**Comment by Mil4n0r** [comment]
I suggested a list of allowed tags in the additional context of the PR (#1765). We can create a discussion related to it if needed.
