### ISSUE TITLE
Include styled components as dependency of the CDK

### ISSUE THREAD

**Issue by kukoc** [dxc-technology/halstack-react#1663]
Creating a new react project with vite and installing halstack CSK is not enough to start importing halstack components. The app compilation would fail until that syled-components package is installed. 

Example:

1. Create a new React App using $ npm create vite@latest
2. Install the `@dxc-technology\halstack-react`  + project dependencies
3. import a Halsack component in the App component
4. Run $npm run dev
5. See the error.

I would expect styled component to be a Halstack project dependency. Moreover, Using the latest version of styled components, I experienced weird behaviours with containers. Halstack should be using a fixed version.

**Comment by GomezIvann** [comment]
This "problem" leads to a larger and much more complex discussion about our dependencies as a library of React components. You can join it here: https://github.com/dxc-technology/halstack-react/discussions/1664.

For the moment and to solve the issue, you can update your local version of `npm` to the 7th and newer to automatically install peer dependencies of libraries in projects (see their [release notes](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies)):
```
npm i -g npm@7.24.2
```
