### ISSUE TITLE
Tabs Component Labels should handle text overflow

### ISSUE THREAD

**Issue by diwakarang** [dxc-technology/halstack-react#1682]
**Describe the bug**
When Tabs label is too long to be displayed inside the available space it should force the text to trucate with ellipsis. That is not working

**To Reproduce**
1. Visit Halstack component website, and add following values to list of tabs
```

     [
          {
            label: "Customer Journey V2 Jan 2023.pdf",
          },
          {
            label: "Market Compensation Levels Report Q1 2023.pdf",
          },
          {
            label: "Market Reform Contract",
          },
          {
            label: "Market Reform Proposal",
          }
     ] 

```

2. It can be noticed that tabs label doesn't get truncated with ellipsis.

**Expected behaviour**
When Tabs label is too long to be displayed inside the available space it should force the text to trucate with ellipsis
As mentioned in the screenshot below.

**Screenshots**
Usage mentioned in [Docs](https://developer.dxc.com/halstack/10/components/tabs/usage/#content)
<img width="902" alt="Tabs" src="https://github.com/dxc-technology/halstack-react/assets/42486284/65518109-e83e-4cb6-be0a-b63f06b9a0d7">

**Additional context**
This is observed, when it is required to use lengthy labels for Tabs

**Add labels**
Tabs, text overflow

**Comment by Mil4n0r** [comment]
The multi-line ellipsis is, as far as I know, a functionality that can be implemented only using `-webkit-line-clamp` (with value 2 in this case), which is not supported by all the browsers. It is also not handled either by our `BaseTypography` which could become a problem due to it being used in order to display the label of the `Tags`.

We should find a way to proceed in order to cover this scenario.

**Comment by kukoc** [comment]
From our doc:

**Comment by Mil4n0r** [comment]
Hello,

Following our discussion, we have decided not to incorporate the requested feature into Halstack. We believe that accommodating long text within the Tabs component does not align with its intended use case.

Thank you in any case for proposing it and helping us to improve.
