### ISSUE TITLE
SideNav

### ISSUE THREAD

**Issue by mmascord** [dxc-technology/halstack-react#170]
The SideNav component does not seem to meet the developer guide lines, as described here:

https://developer.dxc.com/design/components/sidenav

There is no documentation on how to open and close the SideNav here:

https://developer.dxc.com/tools/react/2/#/components/sidenav

It seems the SideNav is fixed, even in the design documentation it states it should be possible to open and close the SideNav.

In contrast the Material UI Drawer components offers many more options for side navigation and comes with excellent examples on how to open and close the component using a hamburger widget here:

https://material-ui.com/components/drawers/

**Comment by jsardid** [comment]
@mmascord we have implemented that functionality as part of our application layout component:
https://developer.dxc.com/tools/react/2/#/components/applicationLayout

Guidelines:
https://developer.dxc.com/design/principles/layout
