### ISSUE TITLE
DxcTextInput - have option for Prefix where it has divider ( | ) sign which is confusing, Couldn't find any option to remove the same

### ISSUE THREAD

**Issue by mjayaraj2** [dxc-technology/halstack-react#1742]
**Is your feature request related to a problem? Please describe.**
In DxcTextInput component, we have option for Prefix where it has divider ( | ) sign which is confusing, Couldn't find any option to remove the same. In US, they always use like this $ 10,000.00 . Need provision to remove the divider

**Describe the solution you'd like**
There should be provision to remove the  divider ( | ) sign

**Describe alternatives you've considered**
Customizing the DxcTextInput which is not the preferrable 

**Additional context**
There should be provision to remove the  divider ( | ) sign

**Add Labels**
Add any applicable labels like related components, services, team or project reporting this new feature... etc.

![DxcTextInputWithDivider](https://github.com/dxc-technology/halstack-react/assets/119607913/03f40539-2059-478f-a22f-61e7e32e81fc)

**Comment by kukoc** [comment]
Hi @mjayaraj2 , Thanks for reaching out. 

Having a divider is a design decision that Halstack Designers can probably justify with arguments like accessibility or readability.  I will let them to comment

**Comment by lcordobapuerto** [comment]
As we've stated before, the presence of a divider in the prefix/suffix our Text input is supported by a design decision to improve the overall user experience and usability of said component. However, we will collect all your valuable inputs to evaluate the possible future addition of an Amount component to Halstack.
Thank you!

**Comment by lcordobapuerto** [comment]
Hi there!
As we've stated before, the presence of a divider in the prefix/suffix in our Text input is supported by a design decision to improve the overall user experience and usability of said component. However, we understand that using a divider in a prefix/suffix of a currency is a special use case, which is why we're collecting all your valuable inputs to evaluate the possible future addition of an Amount component to Halstack. 
In addition, we're always glad to receive contributions, so if you have something in mind, we'll be happy to consider your inputs for this possible new component.
Thank you!

**Comment by GomezIvann** [comment]
As there has been no further activity, this issue is closed.

**Comment by lcordobapuerto** [comment]
Hey there!
We have been thinking about this issue for a while now, do you think this approach could work for you? Can you please check with your team that this is what you are looking for?
![NI - no divider](https://github.com/dxc-technology/halstack-react/assets/147498165/51ba5992-7f72-40e8-bbd9-6af4e06148dd)
Thank you!

**Comment by kukoc** [comment]
@mjayaraj2 , please share your feedback. Thanks

**Comment by mjayaraj2** [comment]
Yes, would prefer to see as below
![DxcTextInputDollarsign](https://github.com/dxc-technology/halstack-react/assets/119607913/9d0b8545-a667-40cb-9933-1e50dc309a8b)

**Comment by GomezIvann** [comment]
> Yes, would prefer to see as below ![DxcTextInputDollarsign](https://private-user-images.githubusercontent.com/119607913/337320740-9d0b8545-a667-40cb-9933-1e50dc309a8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODc0MjMsIm5iZiI6MTcxNzY4NzEyMywicGF0aCI6Ii8xMTk2MDc5MTMvMzM3MzIwNzQwLTlkMGI4NTQ1LWE2NjctNDBjYi05OTMzLTFlNTBkYzMwOWE4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQxNTE4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDBiMmY0MDQwYjdhMTQzYzE4YjQ4N2RmZGI5YmYxM2Y5M2QxMjRhZTRiYTEzMGU0YzhjNWE0YzgzNmZkODBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DlXAGsmPyWh9VHpbRhPaco7OJQlkFYHdwl-lOjkd8Xw)

Hello again!

This image does not correspond to our designers' proposal, but we will do our best to meet your needs. I will work on it.

Thanks!
