### ISSUE TITLE
[DxcButton] "danger" mode

### ISSUE THREAD

**Issue by AlanPadi95** [dxc-technology/halstack-react#1746]
**Is your feature request related to a problem? Please describe.**
I think we need a clear way to show a button with an action that could be dangerous to execute, for example, when you have a button that will remove something permanently from your database.

**Describe the solution you'd like**
The solution I have thought of is to create a new `mode` named `danger` or something like that with the lowest preference in the list of modes that will show the button on a red background.

**Describe alternatives you've considered**
N/A

**Additional context**
An example use case:
![image](https://github.com/dxc-technology/halstack-react/assets/25431024/428c7d78-7351-4a3c-af33-86cf5bbb5696)

**Add Labels**
SaaSOps Automation, CSAM Applications, DxcButton.

**Comment by Mil4n0r** [comment]
This will be covered by the new semantic buttons.
