### ISSUE TITLE
Checkbox not working properly with Resultset Table

### ISSUE THREAD

**Issue by djdannycastillo** [dxc-technology/halstack-react#1752]
**Describe the bug**
When you add a DxcCheckbox component for each item to rows array, checkboxes not being checked separately, instead of, checkboxes are being checked based on index in the pagination. I can checked each checkbox separately if I use checked prop but every time I update the state of the checkboxes, the table is re-rendered and it returns to the first page.

**To Reproduce**
1. Create a simple component using the example in the documentation https://developer.dxc.com/halstack/10/components/resultset-table/

2. Add a DxcCheckbox for each element like this:

`
const rows = [
   [
      { displayValue: <DxcCheckbox /> },
      { displayValue: "001"},
      { displayValue: "Cris"},
      { displayValue: "Paris"}
    ]
 ]`

3. Add more than 5 elements in the rows array, in order to display pagination

4. Check the first DxcCheckbox in the first page and navigate to the others pages, you will see all DxcCheckbox in the first position will be checked

**Expected behaviour**
We want to check each element into the array separately to handle the checkboxes are been checked

**Screenshots**
![checkboxes-resultset-table](https://github.com/dxc-technology/halstack-react/assets/6754259/3e6211f4-5856-4a8b-b4a9-57c581f24dab)

**Comment by GomezIvann** [comment]
Hi @djdannycastillo!

First of all, thanks for the feedback and detailing so much of the bug. It helps a lot!

About the issue, I've reviewed it and you are right. Checking the first row checks the rest of the first rows when there's pagination. We need to address this.

Thanks again for the feedback!
