### ISSUE TITLE
On hover state on secondary button with icon, the icon color is not changing to white.

### ISSUE THREAD

**Issue by Sr44102** [dxc-technology/halstack-react#1764]
Projects :  Assure Cede
The secondary button with icon on hover should change to background purple and the text and icon to white. In current scenario only text and background colors are changing but not icon.
Even the icon color should change to white.

Mouse over on the secondary button with icon. 
Observe that the icon color is not changing to white.
Include steps to reproduce the behaviour.

Example:

1. Create a new React app using Vite.
2. Install `@dxc-technology\halstack-react` package.
3. Click on '...'.
4. Scroll down to '...'.
5. See the error.

Icon color in the secondary button should change to white on hover.

![image](https://github.com/dxc-technology/halstack-react/assets/119670575/e6ba7dfd-d107-40d0-b6e1-725e2a10281d)

**Additional context**

**Add labels**
Add any applicable label like the concerned components or the target version of the Design System where the bug has been found.

**Comment by GomezIvann** [comment]
Hi @Sr44102!

I've checked this scenario and it is working fine (https://developer.dxc.com/halstack/next/components/button/#examples-icons). Please write in a comment your code to see what the possible bug is.

Note that if the icon comes from a URL (`string`), our tokens and CSS styling rules will not be applied to the icon. Maybe that's your problem.

**Comment by prajani4** [comment]
> Hi @Sr44102!
> 
> I've checked this scenario and it is working fine (https://developer.dxc.com/halstack/next/components/button/#examples-icons). Please write in a comment your code to see what the possible bug is.
> 
> Note that if the icon comes from a URL (`string`), our tokens and CSS styling rules will not be applied to the icon. Maybe that's your problem.

Yes, the above mentioned note is our issue, could you please help us how to proceed further with this scenario.

**Comment by rconcepcion3** [comment]
> > Hi @Sr44102!
> > I've checked this scenario and it is working fine (https://developer.dxc.com/halstack/next/components/button/#examples-icons). Please write in a comment your code to see what the possible bug is.
> > Note that if the icon comes from a URL (`string`), our tokens and CSS styling rules will not be applied to the icon. Maybe that's your problem.
> 
> Yes, the above mentioned note is our issue, could you please help us how to proceed further with this scenario.

Hello, yes exactly.. the url-based approach will not work as far as applying styles to the icon on hover. Perhaps you can use the an embedded svg as suggested in the documentation example?

![image](https://github.com/dxc-technology/halstack-react/assets/101174179/d527d94e-16f9-44af-8365-48d72b8fcd78)

*On a separate note, for design in UXPin implementation, this is currently tagged as a known limitation where icons can only be added via url but will not take on dynamic properties depending on the state
