### ISSUE TITLE
DxcSelect crashes application with searchable, multiple and empty array

### ISSUE THREAD

**Issue by djdannycastillo** [dxc-technology/halstack-react#1786]
**Describe the bug**
DxcSelect crashes application when setting select with searchable, multiple and receives an empty array.

**To Reproduce**
Try below component

`<DxcSelect
    label="Select your coworkers"
    placeholder="Choose a colleague"
    options={[]}
    searchable
    multiple
  />`

Example:

1. Try adding the DxcSelect with searchable and multiple option
2. Pass an empty array and you should see app crash

**Expected behaviour**
Avoid app crash when the component receives an empty array

**Screenshots**
![Screenshot 2024-01-29 at 19 18 38](https://github.com/dxc-technology/halstack-react/assets/6754259/581c437a-2e73-4980-82e8-e33c4ec123f9)

**Add labels**
Bug

**Comment by GomezIvann** [comment]
Hello @djdannycastillo!

You are correct, the `DxcSelect` seems to be crushing when the flag `searchable` is true and the list of options is empty. We are going to review this with high priority.

Thanks for the feedback!
