### ISSUE TITLE
Quicknav should support links of depth >1

### ISSUE THREAD

**Issue by diwakarang** [dxc-technology/halstack-react#1802]
**Describe the bug**
Quick Nav doesn't display links of depth >1. Also supported depth level is not explicitly specified in doc.

**To Reproduce**
Use a QuickNav component and pass links of depth more than 1

Example:
<img width="550" alt="image" src="https://github.com/dxc-technology/halstack-react/assets/42486284/51b3ef40-2b24-44a4-be98-891c19797064">

1. In the attached screenshot, it can be observed links of depth =2 is used.
2. Light and Dark values can be traversed in the following order, principles -> themes -> light.
3. However, in the display, only upto Themes is display. Light and Dark are nested within Themes, which are not displayed. 

**Expected behaviour**
1. Good to specify, recommended/max depth of links.
2. Quicknav should support links of specified depth.

**Screenshots**
Attached above.

**Additional context**
If this component, can be enabled to define fragment and label instead of inferring fragments from label order, it would be flexible for users. We are facing the issue in one of API doc based application, where user content is divided into multiple deep levels(depth upto 5) of headings and sections.

**Add labels**
Quicknav, documentation, bug, quick nav

**Comment by GomezIvann** [comment]
Hello, @diwakarang

We are going to review this issue tomorrow. I will come up to you as soon as we reach an agreement on how to proceed with this.

Thanks for the patience!

**Comment by GomezIvann** [comment]
Hello again @diwakarang

Our designer is going to reach you to try to understand your use case. For the moment, we don't see the value of adding a level of depth greater than 1, as the Quick Nav is intended to take up little space and allow navigability between the large sections of a page. For pages with many levels of depth, the solution may lie in the use of another component.

In any case, we agree that we should have better specified and justified this decision in the documentation of our component. We will address this.

Thanks as always for the feedback!

**Comment by diwakarang** [comment]
@GomezIvann 
Thanks for the update.

**Comment by diwakarang** [comment]
Closed by #1810
