### ISSUE TITLE
DxcLink doesn't update the icon color when visited

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-react#1816]
**Describe the bug**
When the link is `:visited` the color of the icon doesn't update to match the current state of the component.

**Screenshots**

<img width="112" alt="Captura de pantalla 2024-02-09 a las 20 10 33" src="https://github.com/dxc-technology/halstack-react/assets/44321109/ce1597cf-cb94-4b7c-8802-8e6183de25f2">

_Screenshot taken in Safari._

**Comment by Mil4n0r** [comment]
This seems to be a safari-only problem:
https://stackoverflow.com/questions/68116594/safari-not-showing-visited-color-for-svg-icon-that-is-inside-an-anchor-tag
