### ISSUE TITLE
Password strength

### ISSUE THREAD

**Issue by hanoj-budime** [dxc-technology/halstack-react#1894]
A password strength indicator is displayed to a user after they have entered a password in a field. It allows the user to understand the strength of a password after it has met the password requirements

![example](https://github.com/dxc-technology/halstack-react/assets/53425981/9f6f43c3-e147-4734-9305-79f985939295)

**Comment by kukoc** [comment]
After investigation, very few Design systems have a password component with opinions on how to validate password rules. However, we see the value in providing a design opinion about it. We are currently exploring creating a Design pattern that can help our users to design such UX  consistently. @hanoj-budime , we will keep you in the loop.

**Comment by hanoj-budime** [comment]
Thank for the update.
