### ISSUE TITLE
ResultsetTable returns to the first page when re-rendered.

### ISSUE THREAD

**Issue by jsuarezgonz** [dxc-technology/halstack-react#1936]
**Describe the bug**
When the resultsetTable is re-rendered it always returns to the first page.
If we have inside the resultsetTable one component that changes its state, independently of the page in which it is when the state changes the resultsetTable returns to the first page.

**To Reproduce**
1. Create a resultsetTable with several pages and with radio buttons in one of its columns.
2. Move to the last page.
3. Click on one radio button.
4. ResultsetTable returns to the first page

**Expected behaviour**
ResultsetTable should stay on the page it was on.

**Comment by Mil4n0r** [comment]
To give some context, the specific case where this occurs is when we are handling the actions in a way that the rows value is modified (for example, when storing checkbox states). This is caused by the `useEffect` that is present in the `ResultsetTable`, which currently has the following:

```
useEffect(() => {
    if (!hidePaginator) {
      rows.length > 0 ? changePage(1) : changePage(0);
    }
  }, [rows]);
```

I think it would be appropiate to adjust the logic, in my opinion the best approach would be to check the previous length of `rows` and compare to the current one. Depending on whether the size remains equal or have changed, we can adjust the page. The logic that I have thought is something like this:

```
if current_rows_length == previous_rows_length:
    // Do nothing
else if current_rows_length > previous_rows_length:
    // Move to the last page (according to the new size)
    last_page = calculate_last_page(current_rows_length)
    current_page = last_page
else:
    // Check if the current page is now empty
    if current_page * page_size >= current_rows_length:
        // Go back to the previous page
        current_page = max(0, current_page - 1)
    else
        // Do nothing
```

**Comment by AlanPadi95** [comment]
Hi!

We have found an issue related to the checkboxes in a ResultsTable. We talked about it with @Jialecl and he recommended us to post the case in a comment on this issue:

![screen-capture-ezgif com-video-to-gif-converter](https://github.com/dxc-technology/halstack-react/assets/25431024/a1acf366-656a-411e-b27e-cc551fa4e514)

When we select an item from the table, the selected status of the checkbox is inconsistent.

Here, you have the implementation of the checkbox in the table cell:

```ts
{
    displayValue: (
      <DxcCheckbox
        defaultChecked={deploymentPackage.isSelected === true}
        disabled={disabled}
        size="fillParent"
        value={`deploymentPackages.${deploymentPackage.id}`}
      />
    ),
    sortValue: `${deploymentPackage.isSelected ?? false}`,
},
```
Thanks, everyone! 😃

**Comment by Mil4n0r** [comment]
> Hi!
> 
> We have found an issue related to the checkboxes in a ResultsTable. We talked about it with @Jialecl and he recommended us to post the case in a comment on this issue:
> 
> ![screen-capture-ezgif com-video-to-gif-converter](https://private-user-images.githubusercontent.com/25431024/323259520-a1acf366-656a-411e-b27e-cc551fa4e514.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDYxNjgsIm5iZiI6MTcxMzQ0NTg2OCwicGF0aCI6Ii8yNTQzMTAyNC8zMjMyNTk1MjAtYTFhY2YzNjYtNjU2YS00MTFlLWIyN2UtY2M1NTFmYTRlNTE0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDEzMTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNGNjYjA2NWJmNTkwY2E0MGVhYzMzNDBlMGY3ZmFlOTY0NjdjZWYwYjk0M2MxODg2NDZlYWI5MDM2Y2VmZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fTHiy-IUlvtzq_z37VjubD43BScF-J8YYxonfYK4Fnk) [ ![screen-capture-ezgif com-video-to-gif-converter](https://private-user-images.githubusercontent.com/25431024/323259520-a1acf366-656a-411e-b27e-cc551fa4e514.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDYxNjgsIm5iZiI6MTcxMzQ0NTg2OCwicGF0aCI6Ii8yNTQzMTAyNC8zMjMyNTk1MjAtYTFhY2YzNjYtNjU2YS00MTFlLWIyN2UtY2M1NTFmYTRlNTE0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDEzMTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNGNjYjA2NWJmNTkwY2E0MGVhYzMzNDBlMGY3ZmFlOTY0NjdjZWYwYjk0M2MxODg2NDZlYWI5MDM2Y2VmZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fTHiy-IUlvtzq_z37VjubD43BScF-J8YYxonfYK4Fnk) ](https://private-user-images.githubusercontent.com/25431024/323259520-a1acf366-656a-411e-b27e-cc551fa4e514.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDYxNjgsIm5iZiI6MTcxMzQ0NTg2OCwicGF0aCI6Ii8yNTQzMTAyNC8zMjMyNTk1MjAtYTFhY2YzNjYtNjU2YS00MTFlLWIyN2UtY2M1NTFmYTRlNTE0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDEzMTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNGNjYjA2NWJmNTkwY2E0MGVhYzMzNDBlMGY3ZmFlOTY0NjdjZWYwYjk0M2MxODg2NDZlYWI5MDM2Y2VmZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fTHiy-IUlvtzq_z37VjubD43BScF-J8YYxonfYK4Fnk) [ ](https://private-user-images.githubusercontent.com/25431024/323259520-a1acf366-656a-411e-b27e-cc551fa4e514.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDYxNjgsIm5iZiI6MTcxMzQ0NTg2OCwicGF0aCI6Ii8yNTQzMTAyNC8zMjMyNTk1MjAtYTFhY2YzNjYtNjU2YS00MTFlLWIyN2UtY2M1NTFmYTRlNTE0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDEzMTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNGNjYjA2NWJmNTkwY2E0MGVhYzMzNDBlMGY3ZmFlOTY0NjdjZWYwYjk0M2MxODg2NDZlYWI5MDM2Y2VmZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fTHiy-IUlvtzq_z37VjubD43BScF-J8YYxonfYK4Fnk)
> 
> When we select an item from the table, the selected status of the checkbox is inconsistent.
> 
> Here, you have the implementation of the checkbox in the table cell:
> 
> ```ts
> {
>     displayValue: (
>       <DxcCheckbox
>         defaultChecked={deploymentPackage.isSelected === true}
>         disabled={disabled}
>         size="fillParent"
>         value={`deploymentPackages.${deploymentPackage.id}`}
>       />
>     ),
>     sortValue: `${deploymentPackage.isSelected ?? false}`,
> },
> ```
> 
> Thanks, everyone! 😃

Hi Alan, first of all thanks for your review.

I would like to see the rest of the code (including the search and the criteria for the `isSelected` property) to be able to provide more details.

From what I can see, what you are currently experiencing is the expected behavior. I assume that the first row (Assure CSAM Console Application) is being checked because of the defaultChecked condition being true. On the other hand, when you are checking one of the boxes, according to the code that you provided it seems that no `onChange` option is set in order to maintain each Checkbox's value updated so, as soon as you rerender the component (for example, changing the page), the value for the Checkbox does not persist by default.

![image](https://github.com/dxc-technology/halstack-react/assets/33158831/4b26cae4-892b-41f2-8c92-3e78db2de112)
AFAIK, you would need to implement something similar to this inside of a loop to achieve the wanted result.

Please let me know if that helps.

**Comment by Mil4n0r** [comment]
Thank you for the feedback @AlanPadi95 , I am currently working on a solution for it.
