### ISSUE TITLE
DXCResultSetTable paginator options missing

### ISSUE THREAD

**Issue by RohiniLAP** [dxc-technology/halstack-react#1942]
DXCResultSetTable is not having currentPage and onPageChange properties

DXCResultSetTable should have currentPage and onPageChange properties
<img width="336" alt="resultsettable_currentPage" src="https://github.com/dxc-technology/halstack-react/assets/166112232/e327eca5-007a-4254-914b-7b52a34eb41a">

**Comment by GomezIvann** [comment]
Hi @RohiniLAP!

In order to add new props as you requested, we need more information about your needs and use cases. Please can you elaborate more on this issue?

Thanks!
