### ISSUE TITLE
Issue with Paginator of ResultsetTable in release 12.0.0 (missing icons?)

### ISSUE THREAD

**Issue by DirkBaumannDXC** [dxc-technology/halstack-react#1948]
**Describe the bug**
Using the release 12.0.0 the paginator of ResultsetTable components show labels instead of icons (see screenshot)
Note: Release 11.0.0 don't have this issue.

**To Reproduce**
Use example app of the halstack-react delivery and use the Release 12.0.0. in the package.json:
...
"@dxc-technology/halstack-react": "^12.0.0",
..

**Expected behaviour**
Paginator should show icons. 

**Screenshots**
![ResultsetTable](https://github.com/dxc-technology/halstack-react/assets/45043117/5340abff-e713-4057-997e-544803c924a3)

**Comment by Jialecl** [comment]
Hello @DirkBaumannDXC ,
We will work on a solution as soon as possible.

**Comment by DirkBaumannDXC** [comment]
Are there plans to provide a bugfix release for 12.0.0 ?
