### ISSUE TITLE
[`DxcContainer`] Unable to define position on `sticky` mode

### ISSUE THREAD

**Issue by AlanPadi95** [dxc-technology/halstack-react#1953]
**Is your feature request related to a problem? Please describe.**
We have a problem related to the `DxcContainer` when is configured to be in a sticky position, and we need to define the position on the screen.

```ts
<DxcContainer
        height="fit-content"
        maxHeight="calc(100vh - 300px)"
        overflow="auto"
        position="sticky"
        style={{ top: "220px" }}
      >
//[...]
</DxcContainer>
```

We have partially solved the problem by passing the `style` prop to the component but we think that this is not the general approach.

**Describe the solution you'd like**
A possible solution is to include new props (top, bottom, left, right) to be able to modify the position of the component.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Add Labels**
CSAM, DxcContainer, props, position, sticky

**Comment by GomezIvann** [comment]
Hello @AlanPadi95!

Can you give me more context about your issue? I have tested your code using our props (`inset` and `position`) and it works fine:

<img width="1280" alt="image" src="https://github.com/dxc-technology/halstack-react/assets/44321109/e5e4756b-e570-453e-bcf2-15faa41803bb">

Thanks!

**Comment by AlanPadi95** [comment]
Hi @GomezIvann!

I have tested our implementation using the inset prop and the container is shown perfectly.

Thanks for your support! And sorry for the inconvenience.

P.D.: You can close this issue if you want.

**Comment by GomezIvann** [comment]
Hi, again @AlanPadi95!

Great to know that it worked.

Thanks to you! 🚀
