### ISSUE TITLE
[DxcContextualMenu] Select an item by default

### ISSUE THREAD

**Issue by jsuarezgonz** [dxc-technology/halstack-react#1962]
**Describe the bug**
We need to define a way of selecting one of the items of the DxcContextualMenu by default. For example, if the initial state of a screen is showing the content of one of the items of the contextual menu, we have no way to show the item as selected.

**Expected behaviour**
We should have a way to select by default one of the items of the DxcContextualMenu and show it in the same way as if it had been clicked.

**Screenshots**
![image](https://github.com/dxc-technology/halstack-react/assets/67998605/5c15a755-3a5d-4101-98ca-6ac206d5fc10)

**Comment by GomezIvann** [comment]
Hi @jsuarezgonz!

Agree on this one. We need to include a new prop or figure out how to allow our users to mark an option as selected by default.
