### ISSUE TITLE
Problem with `DxcDivider` inside fillParent container

### ISSUE THREAD

**Issue by Mil4n0r** [dxc-technology/halstack-react#1995]
**Describe the bug**
There is an unexpected behavior when using a `DxcDivider` inside a `DxcBox` with a column `DxcFlex`. Under these circumstances, the `DxcDivider` has the same length as the content instead of fitting the whole box.

**To Reproduce**
Test the following code:

```
<DxcBox size="fillParent">
  <DxcInset space="2rem">
    <DxcFlex direction="column">
      <DxcTypography>Box</DxcTypography>
      <DxcDivider />
      <DxcTypography>Box</DxcTypography>
    </DxcFlex>
  </DxcInset>
</DxcBox>
```

**Expected behaviour**
The `Divider` should cover the whole box.

**Screenshots**
![image](https://github.com/dxc-technology/halstack-react/assets/33158831/efcac57f-c6b8-44e4-89c3-28013934949f)

**Comment by Mil4n0r** [comment]
This affects the new screen for Assure Answers

**Comment by Jialecl** [comment]
In my opinion the divider is working correctly in this scenario. The width works differently in a flex when the direction is changed to column.

I would change the flex into a grid component:

![image](https://github.com/dxc-technology/halstack-react/assets/12238686/2adbb6c6-f495-448f-ab27-9b4fb0b87cc9)
