### ISSUE TITLE
Selected RadioButton is not visible from the Second page, in table Pagination

### ISSUE THREAD

**Issue by akhilrangu** [dxc-technology/halstack-react#2011]
**Describe the bug**

In table's pagination,  in first page, the selected radioButton is visible and working fine. But from the second page, when a radioButton is selected, it is not visible and defaulting to the first page.

**To Reproduce**
Include steps to reproduce the behaviour.

In a paginated table, 
1. From the first page, select a radioButton, it will work fine.
2. From the second, page(2, 3, 4,.. pages), select a radioButton, it will be not visible and will navigated to 1st page again.

Example:

1. Create a new React app using Vite.
3. Install `@dxc-technology\halstack-react` package.
4. Click on '...'.
5. Scroll down to '...'.
6. See the error.

**Expected behaviour**

**Screenshots**

**Additional context**

**Add labels**
Add any applicable label like the concerned components or the target version of the Design System where the bug has been found.

**Comment by GomezIvann** [comment]
Hello @akhilrangu 

We had a similar issue with the `DxcCheckbox` in the past and it was solved. Can you please share your `@dxc-technology/halstack-react` version and some code snippets to help us understand your problem?

Thanks!

**Comment by GomezIvann** [comment]
Hello again @akhilrangu!

Would you happen to have any updates about this issue?

**Comment by akhilrangu** [comment]
Hi @GomezIvann , 
I'm using  halstack-react version 12.

Please find the below code reference.
Please let me know, if any other details required.
<img width="198" alt="image" src="https://github.com/user-attachments/assets/acdebee1-7bcd-4542-9115-2b7e08da8160">

<img width="193" alt="image" src="https://github.com/user-attachments/assets/9b6ed0de-eb32-47dd-b002-c6bc6069dc38">

**Comment by GomezIvann** [comment]
Hello again!

We had a very similar issue with the `DxcCheckbox` in the past, and it was fixed. Did you try to update to the[ latest version of Halstack](https://github.com/dxc-technology/halstack-react/releases)?

**Comment by Mil4n0r** [comment]
This is supposed to be fixed since version `12.2.0`, please test the same example in that version or higher.

**Comment by akhilrangu** [comment]
Tested with 12.2.0, working as expected.
Thank you.

**Comment by akhilrangu** [comment]
Tested with 12.2.0, working as expected.
Thank you.
