### ISSUE TITLE
Header and cancel button are not aligned in DxcDialog

### ISSUE THREAD

**Issue by akhilrangu** [dxc-technology/halstack-react#2012]
**Describe the bug**

In DxcDialog, the added Header is not aligned with the cancel button.

**To Reproduce**
Include steps to reproduce the behaviour.

Example:

1. Create a new React app using Vite.
2. Install `@dxc-technology\halstack-react` package.
3. Click on '...'.
4. Scroll down to '...'.
5. See the error.

**Expected behaviour**

**Screenshots**

**Additional context**

**Add labels**
Add any applicable label like the concerned components or the target version of the Design System where the bug has been found.

**Comment by GomezIvann** [comment]
Hello @akhilrangu!

I've checked your issue and there are some keypoints to understand. The `DxcDialog` component does not apply any padding to its content, so the alignment needs to be controlled by the user.

If you create a simple Dialog it appears like this:

![image](https://github.com/dxc-technology/halstack-react/assets/44321109/3ca5c313-ab95-4643-bca5-15fd95698649)
```
() => {
  const [isDialogVisible, setDialogVisible] = useState(false);
  const handleClick = () => {
    setDialogVisible(!isDialogVisible);
  };

  return (
    <DxcInset space="2rem">
      <DxcButton label="Enter your data" onClick={handleClick} />
      {isDialogVisible && (
        <DxcDialog onCloseClick={handleClick}>
          Please enter your personal information.
        </DxcDialog>
      )}
    </DxcInset>
  );
}
```
Concluding, the alignment of your header needs to be controlled by you.

If you have any more doubts, please feel free to ask,
Thanks!
