### ISSUE TITLE
DXCResultSetTable, Sorting issue

### ISSUE THREAD

**Issue by jangirkamal123** [dxc-technology/halstack-react#2013]
**Describe the bug**
table having a column with having values of "date string" formatted in 'MM/dd/yyyy'. Sorting on this column is working but 
the arrow of direction on column header is opposite the operation or vice-versa. this is working correct with string and number values but having issue with date.

**To Reproduce**
add date string in sort value in resultsettable. like '01/01/1900', '01/02/1902', '01/01/1901'. the order of sorting is correct but the arrow of direction is incorrect.

**Comment by Jialecl** [comment]
Hello @jangirkamal123 ,

To correctly sort date values use `Date` objects as sorting values instead of strings.

**Comment by jangirkamal123** [comment]
![image](https://github.com/dxc-technology/halstack-react/assets/171939706/5000ba74-cb9c-4049-a9b1-159c2df12049)

![image](https://github.com/dxc-technology/halstack-react/assets/171939706/21941728-2287-4ccc-baf9-eeb653b15ed5)

the code arrangement as you suggested,  is not working in grid

**Comment by Jialecl** [comment]
Hi @jangirkamal123 ,
Can you share with me the code of that table? I will review it in more detail.

**Comment by Jialecl** [comment]
Hello @jangirkamal123 ,

We fixed this issue, it will be included in our next version.

Thanks
