### ISSUE TITLE
DXCDate selector pop up issue

### ISSUE THREAD

**Issue by jangirkamal123** [dxc-technology/halstack-react#2014]
**Describe the bug**
DXC date selector is having its position always downward to the control, so if the control is on bottom of the screen, its getting out of the view.

Unable to inspect, and unable to take screenshot

**Comment by GomezIvann** [comment]
Hello @jangirkamal123!

I've checked your issue and you are right. When the `DxcDateInput` is towards the limits of the screen, the popover doesn't apply the collision detection. We will work on it.

Thanks for the feedback!

**Comment by GomezIvann** [comment]
Hello @jangirkamal123!

We are pleased to tell you that we have added collision detection to the DxcDateInput in the [next](https://www.npmjs.com/package/@dxc-technology/halstack-react/v/0.0.0-9e25510) version of Halstack.

Thanks for the feedback!
