### ISSUE TITLE
Control, maxWidth in the DxcDialog

### ISSUE THREAD

**Issue by akhilrangu** [dxc-technology/halstack-react#2019]
**Describe the bug**
Controlling the maximum width of a dialog ensures that it doesn't become too wide, maintaining readability and aesthetic
alignment within your application's layout.

The dialog size in the one page is different from that of dialog in next page(pagination).

**To Reproduce**
Include steps to reproduce the behaviour.

Add Table(with pagination) with different row/column dynamic sizes within DxcDialog.
Navigate between the pages, and the DxcDialog, will resize.

For more information, please refer the below story.
https://jira.dxc.com/browse/OCARTS-88

Example:

1. Create a new React app using Vite.
2. Install `@dxc-technology\halstack-react` package.
3. Click on '...'.
4. Scroll down to '...'.
5. See the error.

**Expected behaviour**

**Screenshots**

**Additional context**

**Add labels**
Add any applicable label like the concerned components or the target version of the Design System where the bug has been found.

**Comment by GomezIvann** [comment]
Hello @akhilrangu!

We will review this requirement because we are not sure if it is a fair request or if the current behaviour is correct. We will keep you informed.

Thank you for your comments and your patience.

**Comment by GomezIvann** [comment]
Hello again!

After some discussion we have decided that the Dialog is working as expected. By default, the dialog is as large as its content, setting only a maximum width and a minimum width depending on the screen's dimensions. So, for your case, you should define the width at Table level! If you want to stay consistent with the width of your dialogs, set the same size for every table with an `DxcContainer` or as you wish.
