### ISSUE TITLE
DxcInput orientation

### ISSUE THREAD

**Issue by mmascord** [dxc-technology/halstack-react#208]
![Screenshot from 2021-03-23 16-26-14](https://user-images.githubusercontent.com/6444768/112282121-b4156100-8c7e-11eb-9053-b18641c7f577.png)

The application works fine when we use: npm start

When we use: npm run build then there is strange behavior on the DxcInput fields as seen in the attached screenshot the first time we enter the page.  The second time we enter the page it is fine.  This does not happen if we use the Material UI TextField component.

**Comment by jsardid** [comment]
Can you please help us reproducing this issue by creating a repository where we cam see it isolation? We are using npm run build constantly, and we have never seen such behaviour.

Thanks.

**Comment by mmascord** [comment]
We found the issue.  As we use the Material UI library for the Grid, we had imported a slightly different version to that used by the CDK.  We had imported version 4.11.2 and the CDK uses version 4.11.1, so the issue was caused by having two different versions.  We changed to 4.11.1 and it fixed the issue.  Many thanks.  Marcus
