### ISSUE TITLE
Tab underline issue

### ISSUE THREAD

**Issue by mmascord** [dxc-technology/halstack-react#209]
![Screenshot from 2021-03-23 16-25-15](https://user-images.githubusercontent.com/6444768/112283039-9e546b80-8c7f-11eb-95b4-ad186e957100.png)

The tab component works fine with: npm start

When we build the app using: npm run build the tab component does not look good as shown in the attached screenshot.  This does not happen if we use a Material UI tab.

**Comment by jsardid** [comment]
Can you please help us reproducing this issue by creating a repository where we cam see it isolation? We are using npm run build constantly, and we have never seen such behaviour.

Thanks.

**Comment by jsardid** [comment]
@mmascord 

Can you confirm if this issue was also solved with #208 ??
