### ISSUE TITLE
Disabled Button Not Visible in Bloom Theme After Upgrade to Halstack Version 14

### ISSUE THREAD

**Issue by anubhavkushwaha1997** [dxc-technology/halstack-react#2105]
**Describe the bug**
After the upgrade to halstack version 14 , I noticed an issue with the disabled button in the Bloom theme: the disabled button is not visible in the Bloom theme, but it is visible in the Dxc theme.

**To Reproduce**

Example:

To Reproduce:

1.Create a new React app using Vite.
2.Install the @dxc-technology/halstack-react package.
3.Use the Bloom theme in your app.
4.Render a DxcButton component and set it to disabled.
5. Observe that the disabled button is not visible in the UI.
6. Switch to the Dxc theme and note that the disabled button is visible.

**Expected behaviour**
The disabled button should be visible in both the Bloom and Dxc themes.

**Screenshots**
![Screenshot (260)](https://github.com/user-attachments/assets/53809f48-e098-4ba1-b600-5c81ab165be3)
![Screenshot (262)](https://github.com/user-attachments/assets/85fb7043-877d-4ae1-a5a0-10a255b9fc12)

**Additional context**

**Add labels**
This issue i found after upgrading to halstack version 14.

**Comment by GomezIvann** [comment]
Hello @anubhavkushwaha1997!

You are correct. The color calculation of our opinionated theming strategy is not adapting to the bloom theme's main color. We will review this and provide a solution as soon as possible.

Thank you for the feedback!
