### ISSUE TITLE
Autocomplete list not showing in dialog box

### ISSUE THREAD

**Issue by NorbertPointu** [dxc-technology/halstack-react#234]
**Describe the bug**
When we use CDK autocomplete into a dialog box, the suggested list is displaying behind the dialog box. User can not see and select item.

**To Reproduce**
Include steps to reproduce the behavior.

Example:

1. Into a React project
2. Use DXCDialog with overlay=true
3. As children, use DxcInput with autocompleteOptions
4. When input item, the list will not be visible

**Expected behavior**
Let user see the suggested list and be abke to select an item.

**Screenshots**
![image](https://user-images.githubusercontent.com/62135994/115519404-77428700-a289-11eb-847d-d091483ec664.png)

**Additional context**

**Add labels**
Version 3 of React HalStach is used.

**Comment by jsardid** [comment]
Hello @NorbertPointu 

There might be an issue with the z-index when combining those two components. We are looking into it.

Thanks for the feedback
