### ISSUE TITLE
DXCCard :  Image to be optional

### ISSUE THREAD

**Issue by NorbertPointu** [dxc-technology/halstack-react#237]
**Describe the bug**
The DxcCard is waiting for an image. if i don't set any image, i've got a wrong display with a black box. 
In Documentation it seems to be optional : https://developer.dxc.com/design/components/card
![image](https://user-images.githubusercontent.com/62135994/115536386-09eb2200-a29a-11eb-959e-55a7f17b0218.png)

**To Reproduce**

1. Create a new React App using `create-react-app`
2. Install the `@dxc-technology\halstack-react` dependencies and run the app
3. Use DXCCard with no image defined
5. See a black image

**Expected behavior**
- Image to be optional
- Set image size

**Screenshots**
![image](https://user-images.githubusercontent.com/62135994/115532559-34d37700-a296-11eb-8dc2-660e2ed24317.png)

**Additional context**

**Add labels**
React HalStack V3

**Comment by jsardid** [comment]
Thanks for the feedback @NorbertPointu,
We will correct this gap with the guidelines.
