### ISSUE TITLE
DxcSelect - Main screen moved 

### ISSUE THREAD

**Issue by NorbertPointu** [dxc-technology/halstack-react#239]
**Describe the bug**
When we open the select options from component DxcSelect, the body of the page receives the following style: "overflow: hidden; padding-right: 17px;"
The result is the screen is moving

**To Reproduce**

It can be see in the exemple documentation : 
![image](https://user-images.githubusercontent.com/62135994/115535042-af04fb00-a298-11eb-82cc-5341d1f94109.png)

It appears when the main screen has vertical scroll bar

**Expected behavior**

- Main CSS must not be changed
- The screen must not moved.

**Screenshots**
![image](https://user-images.githubusercontent.com/62135994/115535193-d22faa80-a298-11eb-8d67-2037f3d9ee6c.png)
![image](https://user-images.githubusercontent.com/62135994/115535234-d8258b80-a298-11eb-89fe-290428263938.png)

**Additional context**

**Add labels**
React HalStack V3

**Comment by jsardid** [comment]
The new select component comes without material and fixes this issue.
This component is already available in the @next release and will be part of 4.0.0 once we release it during the next couple of weeks.

Thanks for the feedback @NorbertPointu
