### ISSUE TITLE
Layout - Flexbox & grid

### ISSUE THREAD

**Issue by NorbertPointu** [dxc-technology/halstack-react#253]
**Is your feature request related to a problem? Please describe.**
Missing Grid & FlexBox

**Describe the solution you'd like**
Have grid & flexbox
For example as https://getbootstrap.com/docs/4.0/layout/grid/
or https://material-ui.com/system/flexbox/#flexbox

**Comment by aweell** [comment]
Hi @NorbertPointu!

[This functionality](https://github.com/dxc-technology/halstack-style-guide/issues/48) is already present in our roadmap. Please feel free to add there any related feedback :speech_balloon:

Thanks!
