### ISSUE TITLE
[Toggle group] Not selectable using keyboard

### ISSUE THREAD

**Issue by jsardid** [dxc-technology/halstack-react#268]
Toggle group not selectable using keyboard.

**Comment by pwadhwani** [comment]
@jsardid Any update on this issue? Please share ECD. 
Also we found that Calendar icon is also not selectable using keyboard while tabbing. Please suggest if that can be covered under this bug or need to raise separate ticket?

**Comment by jsardid** [comment]
@pwadhwani these two issues have been fixed, and for now they are available in "next".
We'll include these fixes in the next numbered release.
