### ISSUE TITLE
[Select] Component specs

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-react#312]
**[Guidelines specs](https://github.com/dxc-technology/halstack-style-guide/tree/3.1.2/components/select)** for the icon or checkbox size and the spacing of the select component:

Property for single | Value
-- | --
Icon size | 20px x 20px
Spacing between icon and label | 12px

Property for multiple | Value
-- | --
Checkbox size | 20px x 20px
Icon size | 20px x 20px
Spacing between checkbox and label | 12px
Spacing between icon and label | 12px

**Specs image**:

![image](https://user-images.githubusercontent.com/44420072/119556225-0833e300-bd9f-11eb-9441-53787500b5e3.png)

**Implementation**:

![Captura de pantalla 2021-05-25 a las 21 25 30](https://user-images.githubusercontent.com/44420072/119556858-c8b9c680-bd9f-11eb-9216-a8d9b57db8ae.png)

* The space between the checkbox and the edge of the container is more than 16px.
* The `width` and `height` properties of the checkbox don't match either the [checkbox](https://developer.dxc.com/design/components/checkbox) or select guidelines.
* The `height` of the list item in the multi-select should be 48px.
* The checkbox changes the color on hover, there's no hover defined for that component.
* _Should the checkbox receive focus?_ **EDIT**

![image](https://user-images.githubusercontent.com/44420072/119561267-3e746100-bda5-11eb-98aa-ced1226153b3.png)

EDIT: 
* The options list should be entirely focused when displayed, so the focus changes from the input.
* The list options are not accessible by tabbing, only by arrow up and down, so the checkbox never receives focus.

**Comment by marcialfps** [comment]
> * The `width` and `height` properties of the checkbox don't match either the [checkbox](https://developer.dxc.com/design/components/checkbox) or select guidelines.

`width` and `height` are not specified in checkbox and select guidelines.

> * The `height` of the list item in the multi-select should be 48px.

Only in multi-select? Which is the `height` for single?

> * The checkbox changes the color on hover, there's no hover defined for that component.

This component uses internally the DxcCheckbox component, this behaviour is inherited from the component. We can override it or keep it.

> * _Should the checkbox receive focus?_ **EDIT**
> 
> ![image](https://user-images.githubusercontent.com/44420072/119561267-3e746100-bda5-11eb-98aa-ced1226153b3.png)
> 
> EDIT:
> 
> * The options list should be entirely focused when displayed, so the focus changes from the input.
> * The list options are not accessible by tabbing, only by arrow up and down, so the checkbox never receives focus.

This is related with material UI. I'm working on it.

**Comment by aweell** [comment]
> `width` and `height` are not specified in checkbox and select guidelines.

From [current guidelines](https://developer.dxc.com/design/components/checkbox) (not the [ones](https://github.com/dxc-technology/halstack-style-guide/tree/3.1.2/components/select) I edited yesterday):

"Specifications for checkbox are simple. The size of the checkbox should display a box 20 x 20 pixels due to improving the touchable area."

> Only in multi-select? Which is the height for a single?

The height for single remains at 36px (same as react component), the multi-select has more height due to the space the checkbox container takes (20px + focus outline = 26px). We maybe should discuss the [draft](https://github.com/dxc-technology/halstack-style-guide/tree/3.1.2/components/checkbox) (I'm currently editing) of the checkbox component and how is built to avoid having a 36.59x46.59px container.

> This component uses internally the DxcCheckbox component, this behavior is inherited from the component. We can override it or keep it.

We should avoid having to hoverable areas for the same action, my suggestion is to override it, but lets open a discussion also about how to handle this.
