### ISSUE TITLE
onClickSuffix: function is not working for chip

### ISSUE THREAD

**Issue by pwadhwani** [dxc-technology/halstack-react#338]
**Describe the bug**
onClickSuffix: function is not working for chip. 

In CDK developer toolkit, chip with suffix is available but its onClickSuffix function is not working 
onClickPrefix is working fine so raising this bug.
This is part of SOE-21.2 release.
Please share details when can this be delivered.

Screenshot  -

![image](https://user-images.githubusercontent.com/75427388/120640914-a820f900-c490-11eb-9097-2ae14f19ff3a.png)

**Comment by marcialfps** [comment]
Hi @pwadhwani, the bug is fixed and will be available in the 'next' version when the PR is merged to master branch.
