### ISSUE TITLE
CSS Conflicts with makeStyle of Material.ui

### ISSUE THREAD

**Issue by NorbertPointu** [dxc-technology/halstack-react#361]
We use material.ui to handle our CSS by using useStyle = makeStyle()
We use the last version of CDK for many components.

We have no issue in developement env.

When we build the production application and deploy it we got conflicts.

Our analysis is : 
CDK use also Material.ui style (makeStyle or withStyle) and at a moment, in production only, CDK has the same CSS classname as us and It's the CDK css which override the one we made.

Here a screenshot of the conflicts :
In red the CDK CSS in conflicts with our CSS

![image](https://user-images.githubusercontent.com/62135994/123965893-3071bb80-d9b5-11eb-9d00-f0f37573a074.png)

Could you please provide a solution to fix this issue.
Thx,
Norbert

**Comment by jsardid** [comment]
@NorbertPointu 
Those classNames are autogenerated and I can't easily find where they are set.
Can you specify exactly what it is that you are styling and it's getting overwritten?
