### ISSUE TITLE
[Chip] Component specs

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-react#363]
[Component guidelines](https://developer.dxc.com/design/guidelines/components/chip) released in 3.3.0

![image](https://s3.amazonaws.com/design.system.components.catalog/guidelines/components/chip/images/chip_specs.png)

- [x] Add `iconColor` token 

Component token | Element | Token | Value
-- | -- | -- | --
`iconColor` | Icon | `Hal-Black` | `#000000`
`iconColor` | Icon:disabled | `Hal-Grey-L-60` | `#999999`

- [x] Update color specifications

Component token | Element | Token | Value
-- | -- | -- | --
`backgroundColor` | Chip container | `Hal-Grey-S-90` | `#e6e6e6`
`disabledBackgroundColor` | Chip container:disabled | `Hal-Grey-S-95` | `#f2f2f2`
`fontColor` | Label | `Hal-Black` | `#000000`
`fontColor` | Label:disabled | `Hal-Grey-L-60` | `#999999`
`focusColor` | Focus outline | `Hal-Blue-s-35` | `#0067b3`

- [x] Update component `margin` and `padding` values

Property | Element | Value
-- | -- | --
`padding-left/right` | Chip container | 16px
`margin` | Prefix/Suffix | 8px

- [x] Update component `height`

Property | Element | Value
-- | -- | --
`min-height` | Chip container | 40px

**Comment by GomezIvann** [comment]
About the icon color tokens, shouldn't they be named as `iconColor` and `disabledIconColor`?
