### ISSUE TITLE
DxcApplicationLayout.Header z-index clashes with modal from third party library

### ISSUE THREAD

**Issue by NorbertPointu** [dxc-technology/halstack-react#375]
**Describe the bug**
We use a third party library as modal dialog but it's appears under the DXC header.
The ZIndex of Header is bigger of the ZIndex of the modal.

**Expected behavior**
We would like to be able to pass a classname to the DxcApplicationLayout.Header. in that way we will be able to set the zIndex we want for the DXC Header.

**Screenshots**
![image](https://user-images.githubusercontent.com/62135994/130043567-de2d25dd-6b29-497b-acd5-57ee06bb792b.png)

**Comment by jsardid** [comment]
Sorry for the late answer @NorbertPointu.
Can I ask you why are you not using the modal we provide in Halstack? This component should be using the right z-index already.
