### ISSUE TITLE
[Upload] Component specs

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-react#381]
[Component documentation](https://github.com/dxc-technology/halstack-style-guide/blob/master/guidelines/components/upload/README.md) released on 3.8.0

![](https://github.com/dxc-technology/halstack-style-guide/raw/master/guidelines/components/upload/images/upload_preview.png)

- [ ] Increase container padding from 20px to 24px.
- [ ] Review component specs [[1]](#1)
- [ ] Use a button secondary variant instead of using a primary
- [ ] Replace the upload and drop icons to the correct ones:
* Upload: [cloud_upload.svg](https://fonts.gstatic.com/s/i/materialiconsoutlined/cloud_upload/v12/24px.svg)
* Drop files: [copy_all.svg](https://fonts.gstatic.com/s/i/materialiconsoutlined/copy_all/v8/24px.svg)

[1] The component specs have not been released in the documentation since the component is planned to be updated, the specs can be found in the [XD component link](https://xd.adobe.com/view/39b1bdc4-900e-431e-8724-2076a4840509-6ce2/variables/)

**Comment by jsardid** [comment]
Closing this one since we are deprecating this component and replacing it with the file input.
