### ISSUE TITLE
DxcChip size

### ISSUE THREAD

**Issue by AlanPadi95** [dxc-technology/halstack-react#416]
Whenever we have only 1 DxcChip, the complete label is not shown property. It's somehow cut.
However if we have 2, there's no issue with the size, labels are always propertly shown.

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/25431024/139233033-2f842e14-2923-4042-80c5-dca754d5fb99.png)

**Comment by jsardid** [comment]
@AlanPadi95 I can't reproduce this issue. If you check the first example of the documentation site you'll see how there is a long label:
![image](https://user-images.githubusercontent.com/7370399/146262342-5a218706-3d53-46e6-8269-812ff2107bb4.png)

Maybe something related to the context where this is being used? Can you provide further detail?
