### ISSUE TITLE
Type existing components' API

### ISSUE THREAD

**Issue by jsardid** [dxc-technology/halstack-react#473]
- [x] #477
- [x] #478
- [x] #479
- [x] #508
- [x] #509
- [x] #521
- [x] #530
- [x] #540
- [x] #544
- [x] #538
- [x] #550
- [x] #556
- [x] #562
- [x] #563
- [x] #564
- [x] #577
- [x] #585
- [x] #588
- [x] #555
- [x] #576
- [x] #599
- [x] #607
- [x] #633
- [x] #657
- [x] #673
- [x] #593
- [x] #594
- [x] #639
- [x] #559
- [x] #536
- [x] #513
- [x] #525
- [x] #553
- [x] #517
- [x] #574
- [x] #711
- [x] #713

**Comment by marcialfps** [comment]
![image](https://user-images.githubusercontent.com/35959222/156529108-c96e0e05-dc4a-4011-a5f5-efbec0908042.png)
