### ISSUE TITLE
Add visual regression testing with Chromatic

### ISSUE THREAD

**Issue by jsardid** [dxc-technology/halstack-react#488]
## Add visual regression tests

- [x] #511
- [x] #515
- [x] #535
- [x] #516
- [x] #514
- [x] #522
- [x] #532
- [x] #541
- [x] #545
- [x] #539
- [x] #584
- [x] #557
- [x] #580
- [x] #567
- [x] #565
- [x] #578
- [x] #586
- [x] #589
- [x] #554
- [x] #575
- [x] #600
- [x] #608
- [x] #634
- [x] #658
- [x] #674
- [x] #591
- [x] #592
- [x] #640
- [x] #675
- [x] #534
- [x] #512
- [x] #533
- [x] #552
- [x] #518
- [x] #573

**Comment by aweell** [comment]
Fixes added
