### ISSUE TITLE
[ProgressBar] Wrong token in helperText

### ISSUE THREAD

**Issue by Lisa159** [dxc-technology/halstack-react#597]
**Describe the bug**
HelperText in ProgressBar component is using a wrong token for font-family property.

**Expected behavior**
Change **fontFamily** token to **helperTextFontFamily** token.

**Screenshots**
![image](https://user-images.githubusercontent.com/34685461/152157382-12ad3f32-da8d-4a26-8f9e-fd532d792c27.png)

![image](https://user-images.githubusercontent.com/34685461/152157463-e108ade3-13a1-4538-bba3-f588a3bd07ef.png)

**Comment by aweell** [comment]
![bug_catcher](https://user-images.githubusercontent.com/44420072/152159275-589248ee-d7b4-4928-b5b6-ef3420c84884.png)
