### ISSUE TITLE
Visual tests for some user interactions.

### ISSUE THREAD

**Issue by jsuarezgonz** [dxc-technology/halstack-react#628]
We need to investigate how to do, with Storybook, visual regression testing of some user interactions over internal elements, for example, how to test the hover or active state on one option of the Select component.

**Comment by raquelarrojo** [comment]
Done: 
![image](https://user-images.githubusercontent.com/10975289/211507651-05c4520a-2609-4428-8bd6-c3f3cdca17ef.png)
