### ISSUE TITLE
Update Slider label and helper text styles for disabled state

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-react#641]
Styles are missing for label and helper text in disabled mode:

![image](https://user-images.githubusercontent.com/44321109/152797817-36163109-cacb-4b2f-ac60-3319d6cdf8a6.png)

We should add them as it stands in other components such as Text Input or Select.

**Comment by GomezIvann** [comment]
I agree! With value `#999999` both of them.

**Comment by aweell** [comment]
Added the change for max and min labels to the issue

https://github.com/dxc-technology/halstack-style-guide/issues/693
