### ISSUE TITLE
textFontColor token from text button is affecting active state of secondary button

### ISSUE THREAD

**Issue by aalbuerne** [dxc-technology/halstack-react#66]
When a color value is assigned to _textFontColor_ token of the button, this same value is taken by the secondary button to use it in the font color of the active state.

In the default theme, this issues is not perceived since both modes are using the same color.

To reproduce this wrong behavior, just pick a noticeable color for the _textFontColor_ token and click on a secondary button, you will see how this secondary font color is affected by the color picked for the _textFontColor_, which shouldn't be related.

[Screenshot example](https://user-images.githubusercontent.com/36951935/95829232-457ac180-0d36-11eb-9116-28ab95835206.png)

**Comment by marcialfps** [comment]
This bug is solved in release 1.2.1.
