### ISSUE TITLE
[Card] Outlined prop default value

### ISSUE THREAD

**Issue by marcialfps** [dxc-technology/halstack-react#663]
**Describe the bug**
In the documentation, the default value of the outlined prop in Card component is false but it must be true.

**To Reproduce**
1. Add a DxcCard.
2. By default outlined is show.
3. The documentation is wrong.

**Expected behavior**
Outlined prop default value must be false.

**Screenshots**
![image](https://user-images.githubusercontent.com/35959222/153394207-1ad19643-285b-4927-92fb-7a0ad8b58951.png)

**Add labels**
Card, outlined.

**Comment by aweell** [comment]
Related to this issue, what are the expected changes when this prop is set as `true`?

Reading `outlined` as the prop name cames to me a different visual presentation than the one we're currently displaying:

![Screen Shot 2022-02-10 at 12 27 48 PM](https://user-images.githubusercontent.com/44420072/153400117-2685291b-fb1c-46ad-8596-31bb48685afd.png)

_Fig. - Example of the prop outlined_

**Comment by marcialfps** [comment]
Maybe if we change the name it could be more representative. For example, in the Box component we use `shadowDepth` to indicate the size of the shadow. In this case we are forcing it to value `1`, so we can name it as `showShadow` or just `shadow`.
