### ISSUE TITLE
Change button text of component DxcFileInput when multiple property is false

### ISSUE THREAD

**Issue by DirkBaumannDXC** [dxc-technology/halstack-react#676]
The button text in the DxcFileInput component should be changed when the mutiple property is false.
When mutiple property is false the button text is "Select files", but should be "Select file".

The button text should be configurable.

Example:
```
() => {
  const [files, setFiles] = useState([]);

  const callbackFile = (files) => {
    setFiles(files);
  };

  return (
    <DxcFileInput
      label="File Input for single file"
      helperText="Please select one file"
      value={files}
      callbackFile={callbackFile}
      multiple={false}
      margin="medium"
    />
  );
}
```
![dxcFileInput](https://user-images.githubusercontent.com/45043117/153564592-d7638e76-fa39-4b2b-8822-a6974271fb59.jpg)

**Comment by marcialfps** [comment]
@aweell we need to update the single file variant in the design guidelines with the change proposed here.
