### ISSUE TITLE
[Dropdown] Click event is not detected by ClickAwayListener

### ISSUE THREAD

**Issue by marcialfps** [dxc-technology/halstack-react#679]
**Describe the bug**
In a test case if we use `userEvent.click` or `fireEvent.click` on another component when a DxcDropdown is opened the event is not detected and the dropdown is not closed.
This functionality works fine when using the same function on a dropdown item.

**To Reproduce**
1. Create a test.
2. Add several DxcDropdowns.
3. Click on all of them.
4. The different dropdowns are not closed.

**Expected behavior**
ClickAwayListener is not detecting this event.

**Add labels**
Dropdown, ClickAwayListener, MaterialUI, tests.

**Comment by kukoc** [comment]
Fixed with #635  PR
