### ISSUE TITLE
Rendering issue in Discrete Slider

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#69]
**Describe the bug**
When we are using Discrete Slider, we are facing issue. the black dot comes to the left of the amount at starting.
We can replicate this on : https://developer.dxc.com/tools/react/1/#/components/slider
When we decrease the screen size, the black dot gets overlapped with 10000 itself.  
 
  

**To Reproduce**
https://developer.dxc.com/tools/react/1/#/components/slider
Go to Discrete Slider. and give this code.

    <DxcSlider
      minValue={10000}
      maxValue={100000}
      showLimitsValues={true}
      value={value}
      name="input"
      step={10000}
      marks={true}
      onChange={onChange}
      margin="medium"
    />

**Expected behavior**

**Screenshots**

**Additional context**

**Add labels**
Add any applicable label like the concerned components or the target version of the fwk where the bug has been found.

**Comment by jsardid** [comment]
Hello @ppurumala,
It does look like a bug. We are looking into it right now.

Thanks!

**Comment by ppurumala** [comment]
Any update on this? Please inform so that we can update our SM

**Comment by jsardid** [comment]
Hi @ppurumala,

This issue has been fixed in 1.1.1. 

Thanks and regards.
