### ISSUE TITLE
[Tag] Add disabled prop

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-react#709]
The disabled state of the tag has not been included in the component revision and is still missing

![](https://github.com/dxc-technology/halstack-style-guide/raw/master/guidelines/components/tag/images/tag_states.png)

_Fig. - Tag component states_

[Tag documentation in 4.2.0 - Color specifications](https://github.com/dxc-technology/halstack-style-guide/blob/component-tag/guidelines/components/tag/README.md#color)

**Comment by jsardid** [comment]
@aweell 
Since we are waiting for a decision regarding this component, let's keep this one on hold.
