### ISSUE TITLE
[Footer] Update copyright year in the site

### ISSUE THREAD

**Issue by Lisa159** [dxc-technology/halstack-react#719]
**Describe the bug**
Update copyright year in the footer component in the site.

**Screenshots**
![image](https://user-images.githubusercontent.com/34685461/155134450-a3b129a9-5ef5-403b-8a0f-5d181e281ba9.png)

**Comment by GomezIvann** [comment]
Going a little bit further, should we start offering a default value for the `copyright` prop? I see that every app that uses our Footer writes the same string, maybe we should start giving it predefined to avoid this common problem of not updating the year.

**Comment by GomezIvann** [comment]
Update:

- [ ] When copyright is not defined or passed by the user, give a preset value "© DXC Technology 2022. All rights reserved.".
