### ISSUE TITLE
Remove all deprecated props logoSrc/iconSrc

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-react#728]
Remove every prop `logoSrc` or `iconSrc` and change its counterpart, `logo` or `icon` respectively, type to `string | SVG`, since they have been deprecated for at least one release. The components list is below. This also implies a rethink of each component typing, since some use the logo as an alternative to the text, which leads to the usual "one or another, or both, but never any of them" situation, and in many cases is not yet implemented due to the restriction of having to kinds of props for logos (for example, in Chip component).

- [x] Remove deprecated `iconSrc` from Button.
- [x] Remove deprecated `iconSrc` of an option from Toggle Group.
- [x] Remove deprecated `logoSrc` from `socialLinks` in Footer.
- [x] Remove deprecated `iconSrc` from Tabs.
- [x] Remove deprecated `logoSrc` from `steps` in Wizard.
- [x] Remove deprecated `iconSrc` from Tag.
- [x] Remove deprecated `iconSrc` from Accordion and AccordionGroup.
- [x] Remove deprecated `prefixIconSrc` and `suffixIconSrc` from Chip.
- [x] Remove deprecated `iconSrc` and the `iconSrc` of an option from Dropdown.
- [x] Remove deprecated `iconSrc` from Link.

**Comment by marcialfps** [comment]
![image](https://user-images.githubusercontent.com/35959222/159650102-61d5c65e-b9c3-401b-98df-1af4a871524d.png)
