### ISSUE TITLE
styled-components is required, but not installed or documented

### ISSUE THREAD

**Issue by gpfeifer** [dxc-technology/halstack-react#73]
**Describe the bug**
According https://developer.dxc.com/tools/react/1/#/  to use hastack.react in an  existing project:
~~~
  # with npm
  npm install @dxc-technology/halstack-react

  # with yarn
  yarn add @dxc-technology/halstack-react
        
~~~
It is not documented, that you need to install also styled-components.

**To Reproduce**
Include steps to reproduce the behavior.

1. npm create-react-app myapp
2. cd myapp
2. npm install @dxc-technology/halstack-react
3. Add a DxcButton to App.js
4. npm start

You will get this error message:
~~~
Compiling...
/home/gpf/cdk2/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: ENOENT: no such file or directory, stat '/initrd.img'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cdk2@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cdk2@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gpf/.npm/_logs/2020-10-26T09_19_56_415Z-debug.log
~~~

This can be fixed by:
~~~
npm install styled-components
~~~

**Expected behavior**
Either 'npm install @dxc-technology\halstack-react' should install styled-components or it should be documented that styled-components must be installed.

**Comment by jsardid** [comment]
Thanks @gpfeifer ,

This has been fixed recently. Styled-components is actually required and now it's documented in https://developer.dxc.com/tools/react/1/#/

Regards.
