### ISSUE TITLE
Date Picker behaving wierd. Not able to chose the complete date at one go.

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#74]
**Describe the bug**
Date Picker behaving wierd. Not able to chose the complete date at one go.

**To Reproduce**
added Date field on the page from library -> halstack-react
Clicked the date picker to launch the calendar, want to select date 06/25/1975, the moment I select 25 then the calendar gets closed. Then I have to open date picker again, and it shows the current date - the moment I click the year and select a year the popup gets closed, It doenst allow me to chose a month, date, and year at one go. Only by adding manual the date I am successful in entering date.

**Comment by jsardid** [comment]
Thanks Praveen,

You are right. This looks like a bug in the date component. 
We will have look at it ASAP.

Regards.

**Comment by ppurumala** [comment]
Can you please suggest, how to get this fix? what version of halstack-react we need to add?

**Comment by jsardid** [comment]
Hello @ppurumala 

We have just released 1.1.1, which contains the fix for this issue.

Regards.

**Comment by ppurumala** [comment]
The date picker is still very buggy. When I am selecting an year and then proceed to select a date, the year gets reset.
And always on the date picker the current date shows even I am selecting some other date. 
Its very confusing to select a date-month-year from the date picker.

**Comment by jsardid** [comment]
It works fine in the example provided in the documentation site.
https://developer.dxc.com/tools/react/1/#/components/date

Remember there are two types of date components (controlled and uncontrolled). Please make sure you are using them correctly. If the problem persist, please create another issue providing an isolated example.
