### ISSUE TITLE
Minimum number of rows to display on a table

### ISSUE THREAD

**Issue by pcastanoigle** [dxc-technology/halstack-react#75]
**Is your feature request related to a problem? Please describe.**
In the DxcResultsetTable it is possible to define a property "itemsPerPage" to implement the pagination process. It would good if we could have a way to define a "minimum height" or "minimum items number" so, even if the results to be displayed are less than that value, empty rows or the corresponding space is kept.

This way, if we have a table with only two entries, we could define a minimum items number to 5 and the table would take the same space as if we would have 5 entries (the 2 real ones and the 3 added as empty).

**Comment by aalbuerne** [comment]
Do we really want that behavior? I get your point to preserve the same height as if you have all the entries, but from a users' perspective is less impactful the variation of the height than 3 empty rows at the end of the table.

The user could ask several questions:
- Is there missing data on those empty rows?
- Is there any information that is not loaded yet?
- Should I wait until the information is visible to perform any action in the UI?

We should prevent confusion to the user.
What do you think? 🤓

**Comment by jsardid** [comment]
Closing this one because of inactivity.
Additionally we are planning a full review of the table component on this release: https://github.com/dxc-technology/halstack/issues/31
