### ISSUE TITLE
[Chromatic] Focus is not captured with border radius in snapshots

### ISSUE THREAD

**Issue by raquelarrojo** [dxc-technology/halstack-react#759]
Focus built using `outline` and `border-radius` is not captured with border radius in Chromatic snapshots.

Accordion test:
![image](https://user-images.githubusercontent.com/10975289/158423030-25ef3253-1d98-4aa9-9f25-f76d1af14ccd.png)

Snapshot:
![image](https://user-images.githubusercontent.com/10975289/158423163-06d6e7f9-3c53-49ab-9b1c-2ce201747154.png)

This is happening in the tests of `Accordion`, `Date Input`, `Dropdown`, `Application Layout`, `Link`, `Slider`, `Switch`, `Tag` and `Nav Tabs`.

**Comment by GomezIvann** [comment]
We recently updated to the latest version of Chromatic. In this version this problem is solved.
