### ISSUE TITLE
Remove Bloom logo in footer in Bloom Branding

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#76]
**Describe the bug**
Remove Bloom logo in footer in Bloom Branding

**To Reproduce**
Remove Bloom logo in footer in Bloom Branding. The Bloom doesn't need to have that.

**Comment by jsardid** [comment]
Hi Praveen,

This is not an issue with the CDK.
I guess you want to modify a specific theme in an Assure Platform environment. Isn't this something something you can do using the UX Configuration Application in that environment?

Regards.
