### ISSUE TITLE
[Chromatic] Resultset table header focus is not fine in snapshots

### ISSUE THREAD

**Issue by raquelarrojo** [dxc-technology/halstack-react#763]
Header focus in Resultset table is fine in canvas:

![image](https://user-images.githubusercontent.com/10975289/158547450-4b310aa3-0fb3-4ce2-b695-ddbe3f300766.png)

But it is not in the snapshots:

![image](https://user-images.githubusercontent.com/10975289/158547866-aad64dad-2c5a-4cd7-8b7d-b7cb792003c9.png)

This is happening in `Ascendent sorting` and `Descendant sorting` tests.

**Comment by Lisa159** [comment]
Looks like the problem is fixed after changing the focus outline style from auto to solid.
