### ISSUE TITLE
Provide a type declaration file for TypeScript

### ISSUE THREAD

**Issue by gpfeifer** [dxc-technology/halstack-react#77]
**Is your feature request related to a problem? Please describe.**
When using TypeScript an import like this:
~~~
import { DxcInput } from '@dxc-technology/halstack-react';
~~~
will yield to an compile error:
~~~
Could not find a declaration file for module '@dxc-technology/halstack-react'.
~~~

**Describe the solution you'd like**
Type declaration file provided by DXC

**Describe alternatives you've considered**
There are several workarounds, but a _real_ type declaration file would be ideal.

**Comment by jsardid** [comment]
We are finally taking this one up on this release.
Closing this issue since we have a roadmap item already available: https://github.com/dxc-technology/halstack/issues/5

Thanks for the feedback @gpfeifer
