### ISSUE TITLE
There is no onClick function available for DxcLink component

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#79]
**Describe the bug**
There is no onClick function available for DxcLink component

**Expected behavior**
There should be a onClick function available. We have a requirement, where we need to show an link and on click of that link we want to do some processing and do an task.

**Comment by jsardid** [comment]
We are thinking about implementing a solution similar to this:
https://developer.microsoft.com/en-us/fluentui#/controls/web/link#usage

> When a link has an href, it renders as an anchor tag. Without an href, the link is rendered as a button

It needs to be rendered as a button for accessibility reasons, but it will be styled as a link.

We will keep you updated with the implementation of this enhancement.

Thanks for the feedback.

**Comment by pwadhwani** [comment]
Hi Jesus, Do we have any update on this implementation.

**Comment by jsardid** [comment]
TO DO:
- Add onClick property to DxcLink component
- When DxcLink receives an action, it must render as a button, keeping the same visual style.
