### ISSUE TITLE
Design tokens architecture review

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-react#818]
## Epic description

There's a disconnection between the current global tokens documented by design and the implementation in `variables.js`. The first step of reviewing the design tokens is an update in the list and naming conventions of the global tokens to end matching the connections between them and the component tokens with an alias layer, this layer is meant to bring context to the token usage avoiding using fixed values.

# 22.2

- [ ] #831
- [ ] #947
- [ ] Update variables.js with new global tokens

-------
# 22.3

- [ ] #962
- [ ] Review css properties not using tokens

![image](https://user-images.githubusercontent.com/44420072/162205109-4c2e54d6-bd04-4d4f-967a-719f4efd6d2d.png)

**Comment by GomezIvann** [comment]
Our current plan for tokens has changed radically. All architecture-related issues will be closed.
