### ISSUE TITLE
DXCToggle component not present in new cdk library.

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#83]
**Is your feature request related to a problem? Please describe.**
We have a need where we have to show, a component on the screen like a toggle button. like: Yes/No button.
There was DXCToggle in old library-> dxc-react-cdk. We want same thing to be available in new CDK library -> halstack-react.
The Theming should also be applicable on it.

**Comment by jsardid** [comment]
We have just published release 1.2.1, which includes this new feature.

Thanks for your feedback.
