### ISSUE TITLE
Company logo should not be there on Footer and the footer should look different

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#84]
**Describe the bug**
We have a  requirement, that we don't want a company logo in the footer. 
Also we have a requirement of footer with a different look. Attached below.

![Expected_Footer](https://user-images.githubusercontent.com/72923647/99356294-efb6ad80-28cf-11eb-8e15-2765ecb77fc7.JPG)
![Current Footer](https://user-images.githubusercontent.com/72923647/99356299-f0e7da80-28cf-11eb-8690-1bbf293cdab9.JPG)

Please tell, if this is possible. If yes, by when can we expect the changes.

**Comment by jsardid** [comment]
We are going to allow removing the default logo by explicitly passing the logoSrc as null.
Not sure what you mean by "a different look". Please create a different issue for that, and elaborate a bit more on why or when do we want this new look.

**Comment by peibolsang** [comment]
@ppurumala This is not the right place for this issue. Please create a new issue in our Design Guidelines explaining why this is required https://github.com/dxc-technology/halstack-style-guide/issues. I am closing this one now. Thanks a lot again.
