### ISSUE TITLE
New Components: Data Visualization

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-react#843]
## Effort:  

Design and develop data visualization components to include in product dashboards (Bar, line, pie charts...) This requirement is a low-level requirement, and it is needed to gather insights about what are the exact needs of the product teams. 

* Create / Update UI Kit component(s) 
* Create component documentation 
* Implementation of the component in CDK’s 

The actual solution relies on custom solutions or using 3rd party libraries. In our pursuit of coherence within our set of applications, data visualization components should meet standard criteria and come with clear and concise usage guidelines. 
 
## Impact 

Product teams: Instead of building from scratch or understanding how to consume components from a 3rd party library, a centralized well documented assets can be a game changer in terms of design development speed.

**Comment by Mil4n0r** [comment]
@GomezIvann Please link the BarChart PR to this issue.

**Comment by GomezIvann** [comment]
We are closing this one since it is an investigation task. It is a never ending one so I prefer do keep creating smaller and more specific ones.
