### ISSUE TITLE
Define iconography guidelines/libraries

### ISSUE THREAD

**Issue by jsardid** [dxc-technology/halstack-react#844]
## Effort 
Iconography is one of the core pillars of the design language within a system (apart from color, typography, layout, or illustration).  
- Research different approaches to define our icon assets (appearance, visual weight, sizing scale, etc...) 
- Define a base list where to start exploring visual representation (application UI, business oriented). What elements do we need to build any generic UI? 
- Define the way icons are going to be living inside the library, and the way to consume them. 
- Illustrate and test consistency between icon sets. Iterate to reach a first version of a basic set. 
- Document guidelines about icon usage and how to match the coherence if a third-party asset needs to be used. 
- Implement and test the library in the CDKs. 

## Impact  
- **End customer**: Improvements in the perception of visual coherence between application iconography sets. 
- **Product teams**: Easy to access assets and guidelines

## Related tasks

- [ ] https://github.com/dxc-technology/halstack-style-guide/issues/709

**Comment by GomezIvann** [comment]
This epic has been recently resolved with the new icons approach and documentation page on the Halstack site: https://developer.dxc.com/halstack/next/principles/iconography/.
