### ISSUE TITLE
Optimize the build process of halstack-react

### ISSUE THREAD

**Issue by jsardid** [dxc-technology/halstack-react#846]
## Effort
Research the different strategies for package size optimization and apply them to our Halstack React/Angular libraries. Currently, our build process is quite basic (using rollup). Nowadays tooling has improved a lot, making the process faster and optimizing the bundle size. In addition, we could improve the developer experience of the core team, by using a tool like turborepo, which should simplify the management of a monorepo.

An example of turborepo for a Design System: https://github.com/vercel/turborepo/tree/main/examples/design-system

## Impact  
**End customer**: smaller package size means a faster first load of all our applications using Halstack. The end customer will benefit from this task by interacting with higher performant applications.

**Comment by GomezIvann** [comment]
Our libraries have already been optimised. The only one remaining is @dxc-technology/halstack-react. We need to investigate this one.

**Comment by Mil4n0r** [comment]
Can we close this based on the monorepo PR (#2030)? @GomezIvann @Jialecl

**Comment by GomezIvann** [comment]
Yes! We can definitely close this.

**Comment by GomezIvann** [comment]
Yes! We can definitely close this.
