### ISSUE TITLE
Define Design System governance process

### ISSUE THREAD

**Issue by jsardid** [dxc-technology/halstack-react#847]
- [x] https://github.com/dxc-technology/halstack-style-guide/issues/665

**Effort:**  
Documenting a process flow for governance is an important piece of the contribution model and feedback loop of a design system. It can set clear boundaries between the core team responsibilities and product teams while embracing component/pattern deviations.  

- Discuss and define the governance process that better fits our work culture and product vision. 
- Create and provide accessible and clear documentation about the process. 
- Advocate across the different product teams about the defined model. 

**References:** 
 
Brad Frost: [A design system governance process. Article.](https://bradfrost.com/blog/post/a-design-system-governance-process/) 
Inayaili León: [Vanilla Framework V1. Case Study.](https://yaili.com/project/vanilla-framework) 
 

**Impact:**  
Product teams: Change the current model of “request” to a more collaborative and dynamic process trying to solve the following concerns trough governance documentation: 

- They cannot find a component that does what they need 
- A design system component gets them 90% of the way there, but not 100% 
- They have questions or concerns about the design system

**Comment by GomezIvann** [comment]
We are closing this issue since we have already defined and documented our internal processes.
