### ISSUE TITLE
New Components: Time picker

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-react#852]
## Effort 

Currently, we do not have within the design system components catalog a viable solution to pick time values. To avoid the usage of select or third-party solutions that can impact on the application's visual coherence and user experience we consider that it is important to have an opinion regarding this matter. 

* Research and define a time picker solution. 
* Design and document time-picker component. 
* Specify the component technical design, properties, and behavior 
* Implementation of the component in CDKs. 

## Impact

Product teams: Have a standardized solution for time selection available in Halstack design system. 

## Action items 

- [ ]  https://github.com/dxc-technology/halstack-style-guide/issues/128

**Comment by GomezIvann** [comment]
Moved to discussions.
