### ISSUE TITLE
New Component: Content menu & local nav

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-react#853]
## Effort:  

Include the content menu and local navigator components designed for CSAM into Halstack design system. 
 
* Create / Update UI Kit component(s) 
* Create component documentation 
* Implementation of the component in CDK’s 

## Impact:  

Product teams: Both components add two new dimensions to content navigation providing a way to design better information architecture and a clear component hierarchy when designing and developing complex user flows. 

## Related tasks

- [ ] #824

**Comment by jsardid** [comment]
Duplicated: https://github.com/dxc-technology/halstack-react/issues/824
