### ISSUE TITLE
[File-input] Update component tokens 

### ISSUE THREAD

**Issue by raquelarrojo** [dxc-technology/halstack-react#865]
- [x] Rename `fileItemIconColor` as `deleteFileItemColor`.
- [x] Rename `hoverFileItemIconBackgroundColor` as `hoverDeleteFileItemBackgroundColor` and update value to `color-grey-a-100`.
- [x] Rename `activeFileItemIconBackgroundColor` as `activeDeleteFileItemBackgroundColor` and update value to `color-grey-a-300`.
- [x] Rename `focusFileItemIconBackgroundColor` as `focusDeleteFileItemBorderColor`.

**Comment by Lisa159** [comment]
Tokens `filePreviewBackgroundColor` and `filePreviewIconColor` need to be added.

**Comment by Lisa159** [comment]
Also, add tokens `errorFilePreviewBackgroundColor` and `errorFilePreviewIconColor`.

**Comment by aweell** [comment]
I added a missing component token in the docs in #909
