### ISSUE TITLE
[Layout] Create documentation pages

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-react#866]
## Story description

Create documentation pages for the following components:

- [x] Stack component documentation page
- [x] Row component documentation page
- [x] Bleed component documentation page
- [x] Inset component documentation page

**Comment by aweell** [comment]
Should we indicate in both row and stack doc pages the lack of support for the `gutter` prop in IE and in iOS versions older than 14.5?

I made a workaround using the `@supports` CSS at-rule but not sure if it working properly...

```
@supports not (gap: var($value)) {
  .gutter-#{$name}{
    padding-top: var($value);
    }
  }
  @supports (gap: var($value)) {
 .gutter-#{$name} {
    gap: var($value);
   }  
  }
 }
```

Still needs work since we need to point all children of the `row` and `stack` divs unless the first one using pseudo-selectors.

**Comment by marcialfps** [comment]
I have added a warning message on both row and stack doc pages. As these are experimental components, we can remove the warning when it is fixed.

**Comment by marcialfps** [comment]
![image](https://user-images.githubusercontent.com/35959222/163128625-d8e81cef-34cb-4541-a33c-21d375a0ad15.png)
