### ISSUE TITLE
Review example component

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-react#867]
## Story description

Update the [example component](https://github.com/dxc-technology/halstack-react/blob/master/docs/src/pages/components/common/Example.jsx) following design recommendations and re-using current system components.

### Current example component

![Screen Shot 2022-04-04 at 1 21 52 PM](https://user-images.githubusercontent.com/44420072/161533611-a0177e8a-e173-4ec8-bab1-371d8b575d6f.png)

_Figure 1 - Expanded example component_

### Proposal

[WIP] https://xd.adobe.com/view/b155ebb4-bb61-4d9d-9885-ae1d9cdf0c44-e406/

The current component can be improved by:

* Using a background that enables the visualization of transparent elements/background
* Enable the users to copy the example code in one click
* Position the trigger of the collapsable element in the correct position
* Remove the title of the example since the section should provide a correct heading * description (optional)
* Update [LiveEditorTheme](https://github.com/dxc-technology/halstack-react/blob/master/docs/src/pages/components/common/liveEditorTheme.js) colors using the Halstack onDark palettes

### References

* [Atlassian DS - Button example](https://atlassian.design/components/button/examples)

**Comment by GomezIvann** [comment]
I add some topics to discuss this:

- Error styling.
- Align items to the center of the preview container plus having a default padding, should we keep that or let each example decide its distribution? (as Atlassian).
- Include a linear background to help the user distinguish which components have a background color and which ones don't.

![image](https://user-images.githubusercontent.com/44321109/164170271-50c3e605-3381-444a-9a74-80f51ce5dfa8.png)

- **Actions below.** After using this design for a while, I find it a bit annoying to have the buttons at the bottom, as in most cases the live editor pulls them out of the current page scroll.

**Comment by aweell** [comment]
Thanks @GomezIvann for your feedback 😃 

#### **Error styling**

> Should we keep the current styles as it stands or change them?

I would keep them for the moment, being sure that the same padding used for the examples is applied for the error.

#### **Align items to the center of the preview container**
>shouldn't we keep that or let each example decide its distribution? (as Atlassian). Also, some components sizes are `fillParent`, so setting the display to flex to justify the content to the center may shrink its size and show them very small.

Agree that we should remove the content alignment.

#### **Setting a default padding and how to inform the user about it**

> I can figure that this preset padding is just to avoid issues with the border-radius and the components, but I find a bit intrusive to have an external css rule which the user can't control, since this live editor should be as clean as possible to operate and "play" with the code.

I don't see a direct relationship between having `padding` for the examples and not being clean and easy to operate (and the user can always see to whose box the `padding` belongs through the inspector), I still think that there should be breathing space between the box border and the example elements.

#### **Actions below** 
> After using this design for a while, I find it a bit annoying to have the buttons at the bottom, as in most cases the live editor pulls them out of the current page scroll.

Agree, we can keep actions just below the example box in both cases instead of being pushed by the code box.


#### **Copy action feedback** 

> Since we don't have a tooltip prop or component, how we are gonna let the user know when the code is already copied?

100% on this, we cannot use title and the tooltip component implementation is completely out of scope. I think we should discuss this one in detail.

**Comment by GomezIvann** [comment]
About the padding, I agree we should have one, since some components to work well with the rounded corners, but, what I suggest is that we should inform visually the user that the preview container has a padding not related to the current component being displayed. For example, [Kaizen](https://cultureamp.design/components/button/) have a pretty decent solution to this:

![image](https://user-images.githubusercontent.com/44321109/165039624-498289d0-6194-462c-860a-e28666ecb37e.png)

Maybe the outermost background been white and the inner the linear one... what do you think?

**Comment by GomezIvann** [comment]
This component has been reviewed for the new site, so I mark this as closed.
