### ISSUE TITLE
Need a new design in the footer

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#87]
Need a new design in the footer

Below is the footer we require.
![Expected_Footer](https://user-images.githubusercontent.com/72923647/99788193-c3f12d00-2b46-11eb-84c0-5ea0c4aaee52.JPG)

Please tell if you can achieve this footer design or not possible to achieve?

**Comment by peibolsang** [comment]
Hello @ppurumala. This is not the right place for this issue. Please register a feature request in our Design Guidelines repository https://github.com/dxc-technology/halstack-style-guide/issues indicating why this is needed together with a bit more context. I am closing this issue now. Thanks a lot for your feedback.
