### ISSUE TITLE
[Layout] Review layout components for final release

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-react#884]
- [x] #1209

**Comment by GomezIvann** [comment]
# New Layout components

After some discussions, the final approach involves two new Layout components:

1. DxcRows 
2. DxcRow
3. DxcColumns
4. DxcColumn

## DxcRows and DXColumns - API

My proposal is:

Name | Type | Default value | Prop description
| :-- | -- | -- | -- |
| `gutter` | `Gutter` | "none" | Spacing between stacked elements |
| `divider` | `boolean` | false | Add a divider between stacked elements |
| `align` | `Align`  | `start` | Align columns in the cross axis  |
| `as` | `string` | `div` | Set the component to a different HTML tag |
| `wrap` | `boolean`  | "true" | Wrap elements preventing overflow |
| `reverse` | `boolean`  | `false` | Change the `flex-direction` of the row to `reverse` |

being Gutter:
```
type Gutter = "none" | "xxsmall" | "xsmall" | "small" | "medium" | "large" | "xlarge" | "xxlarge"
```

and Align:
```
type Align = "start" | "end" | "center" | "baseline" | "stretch";
```

### Questions

1. Naming of `gutter` prop. Would `space` or `gap` fit better?
2. With the current approach we can't

**Comment by marcialfps** [comment]
- [ ] Implement DxcRow and DxcRows components.
- [ ] Implement DxcColumn and DxcColumns components.
- [ ] Implement DxcInline component.
- [ ] Implement DxcStack component.

**Comment by GomezIvann** [comment]
After many discussions, we have decided that we don't have enough knowledge to define layout components with a specific context, such as Stack/Inline or Rows/Columns. For now, we are going to add a new component Flex, with a more flexible and primitive context, to try to adapt to more situations and bring more options to the user so he/she can build its layouts.

## Flex

A primitive component that can be used to build flexbox-based elements and layouts.

### API

By default, the `display` attribute would be set to `flex`:

Name | Type | Default value | Prop description
| :-- | -- | -- | -- |
| `as` | `string` | `div` | Set the component to a different HTML tag. |
| `direction` | `row` or `row-reverse` or `column` or `column-reverse` | `row` | Items direction inside the flex container. |
| `wrap` | `nowrap` or `wrap` or `wrap-reverse` | `nowwrap` | Wrap into multiple lines. |
| `grow` | number (no negative numbers) | 0 | Sets the flex grow factor of a flex item's [main size](https://www.w3.org/TR/css-flexbox/#main-size). |
| `shrink` | number (no negative numbers) | 0 | Defines the ability for a flex item to shrink if necessary. |
| `basis` | string | `auto` | Defines the default size of an element before the remaining space is distributed. | 
| `justify-content` | ? | `flex-start` | Defines the alignment along the main axis. |
| `align-content` | ? | `normal` | Defines the alignment along the cross axis. 
| `align-self` | ? | `auto` | The align-self CSS property overrides a grid or flex item's `align-items` value.
| `align-items` | ? | `normal` | Controls the alignment of items on the Cross Axis.
| `children` | `React.ReactNode` | - | Content. |
