### ISSUE TITLE
[Dropdown] Label and options ellipsis

### ISSUE THREAD

**Issue by marcialfps** [dxc-technology/halstack-react#900]
**Describe the bug**
Design guidelines don't specify how the component should work when long texts are used in dropdown label and options.

**To Reproduce**
Currently, React and Angular CDK work differently when using long texts:

_Angular_
![image](https://user-images.githubusercontent.com/35959222/156326890-7d21cc9d-69d1-405d-a912-2b73a498572a.png)
![image](https://user-images.githubusercontent.com/35959222/156327203-e0237ecf-deb7-4737-8bdd-8f37c56d9931.png)

_React_
![image](https://user-images.githubusercontent.com/35959222/156327053-587b1512-88a0-4750-9685-4abf7e4a8294.png)
![image](https://user-images.githubusercontent.com/35959222/156327294-5eaf7dad-8438-4381-bf7e-9c2db6b4aab7.png)

**Expected behavior**
Ellipsis should be considered in the guidelines.

**Add labels**
Dropdown, label, option, ellipsis.

**Comment by GomezIvann** [comment]
I'm closing this issue since the Dropdown was reimplemented to fit the longest label and separate its width from the trigger.
