### ISSUE TITLE
Need ability to put a currency symbol and amount formatting on Slider component

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#91]
Need ability to put a currency symbol and amount formatting on Slider component

We want the amount on the slider to be displayed as **$10,000 and $1,00,000**.
Please note the dollar sign and comma in the amount

![Slider](https://user-images.githubusercontent.com/72923647/99955923-25193a80-2dab-11eb-92f1-369690db8dc0.jpg)

Please do tell us if this is possible in any way?

**Comment by peibolsang** [comment]
@ppurumala This is not the right place for this issue. Please report this issue in the Style Guide repository https://github.com/dxc-technology/halstack-style-guide/issues. I am closing this one now. Thank you
