### ISSUE TITLE
Cognito Login Issue

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-react#92]
Analysis on using CDK Login -

While implementing the login screen using cdk login library, we were facing issue of caching. Once a user logs in, it doesn’t ask for credentials again as it gets stored in cache the first time itself.

Regarding this issue, we had discussion with Jesus. He told that cdk login library should be used if whole application is accessible after login only.
While in our case, quote is not under login ambit and the application screen resides under login ambit.
So he suggested us to develop our own login screen, which needs to interact with Cognito directly.

We wanted to know, if we will get a fix for Cognito Login which will support our case (quote is not under login ambit and the application screen resides under login ambit.) or this is not achievable?

Wanted this information, so that we can plan our stories accordingly.

**Comment by peibolsang** [comment]
@ppurumala I am closing this issue. This is not something that should be discussed in this channel
