### ISSUE TITLE
Inconsistency for required Text Input and Checkbox

### ISSUE THREAD

**Issue by idimovska** [dxc-technology/halstack-react#925]
There is an inconsistency if we need a **Text input** and **Check box** to be mandatory fields(required).
For Check box there is a **required:boolean** prop (If true, the checkbox will change its appearence, showing that the value is required.)
For Text Input it is missing such a prop required. There is an **optional: boolean** prop (If false, will be considered required )

The 2 types of fields look really different and inconsistent: the Check box has a red asterisk and the Text Input has not(if optional=false).

**Expected behavior**
Unify the look of the 2 components if the field is required(mandatory).

![2022-04-21 16_14_35](https://user-images.githubusercontent.com/81325701/164466004-4ef41a16-ae18-4623-96e7-fbb221eedbdf.png)

**Comment by jsardid** [comment]
You are totally right, these two systems shouldn't be living at the same time.
We are [planing a redesign for the checkbox](https://github.com/dxc-technology/halstack-react/issues/877) component which includes replacing `required` with `optional`. But this redesign won't happen at least for some months. @aweell do you think we can bring the optional functionality now (before the redesign)?

**Comment by aweell** [comment]
Thanks @idimovska for your feedback!

100% on this, we can split the redesign into two stages, prioritize making a quick fix to the `required` prop in order to keep consistency, and then allocate the rest of the epic tasks in another release.

**Comment by GomezIvann** [comment]
I split this issue since we need to fix this in more than one component:

- [ ]  [Major] Replace `required` prop with `optional` in Checkbox component
- [ ] [Major] Replace `required` prop with `optional` in Switch component

**Comment by GomezIvann** [comment]
A new `optional` prop has been added to replace `required` in Switch and Checkbox components for consistency between Form components.

![image](https://user-images.githubusercontent.com/44321109/165714838-44263334-d26a-48ec-8659-c691b82ed317.png)
![image](https://user-images.githubusercontent.com/44321109/165714945-7c04f3ee-2e4d-468d-8230-b35b26fc2189.png)
