### ISSUE TITLE
'Optional' hard-coded label for Text Input

### ISSUE THREAD

**Issue by idimovska** [dxc-technology/halstack-react#926]
If optional=true for Text Input => the input will be optional, showing (Optional) next to the label. 
This label is hard-coded and can't be translated if we use another language than English for the UI.

![image](https://user-images.githubusercontent.com/81325701/164467441-d5bff0da-7fbe-4cac-83ce-2cea6b88e5da.png)

**Comment by jsardid** [comment]
Hi @idimovska,

Although we don't have a lot of hardcoded strings in the design system, none of them is allowing for internationalization right now.  So this issue applies to other components of the design system and not just to the "optional" string. For this reason I've just created #929 and I'm closing this one. You can keep track of the discussion there.

I think we should be able to provide a solution soon. 
Thanks a lot for the feedback.
