### ISSUE TITLE
Vulnerability in dependency "moment"

### ISSUE THREAD

**Issue by DirkBaumannDXC** [dxc-technology/halstack-react#931]
There was a "high severity" vulnerability reported for the dependency "moment".
See: https://github.com/advisories/GHSA-8hfj-j24r-96c4 or https://security.snyk.io/vuln/SNYK-JS-MOMENT-2440688

The version currently specified in the package.json is "2.24.0".

Please update to a patched version (version 2.29.2 or higher).

**Comment by jsardid** [comment]
Thanks @DirkBaumannDXC, we'll take this one on priority,
