### ISSUE TITLE
Form components label/helperText/error spacing update

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-react#991]
Focus review (#990) has force us to update the spacing between the component and the label/helperText/error, from `4px/0.25rem` to `8px/0.5rem`:

![image](https://user-images.githubusercontent.com/44321109/170077775-0d9edc2d-504b-4f43-988d-4585ecfd93ad.png)

Summary of components to update:

- [x] Date/Number/Password/Text input
- [x] File Input
- [x] Textarea
- [x] Select
- [x] Radio Group
- [x] Slider
- [x] Toggle group

Document all these changes and bring them into the design libraries:

- [ ] Date/Number/Password/Text input
- [ ] File Input
- [ ] Textarea
- [ ] Select
- [ ] Radio Group
- [ ] Slider
- [ ] Toggle group

**Comment by jsardid** [comment]
Waiting for onDark strategy
